Github actions sync branch on push
RedHatInsights/tower-analytics-frontend pull request #1013
Opened 2023-11-14 09:46 UTC by dmzoneill

sync devel to master

2023-11-14 14:28 UTC, fullsushidev requested changes

2023-11-14 14:28 UTC, fullsushidev commented on .github/workflows/devel.yml
> +          node-version: 12
why node version 12?

2023-11-14 14:32 UTC, fullsushidev submitted a review, later dismissed
is there a specific reason why are we not using the latest versions of the actions?

e.g.:
```
codecov/codecov-action@v3
actions/checkout@v4
actions/setup-node@v4
```

2023-11-14 14:32 UTC, fullsushidev commented on .github/workflows/devel.yml
> +          node-version: 12
Shouldn't we use at least v18?

2023-11-29 10:11 UTC, dmzoneill commented on .github/workflows/devel.yml
> +          node-version: 12
This has nothing to do with our code, it has to do with the code in the github action.
The author of the action indicates version 12.  So we use version 12.

2023-11-29 15:00 UTC, h-kataria approved these changes

2023-11-30 10:05 UTC, merged