Feture: Generalised Charts
RedHatInsights/tower-analytics-frontend pull request #230
Opened 2020-08-05 10:54 UTC by brumik

#220 

@kialam @Ladas 

This is how I started out with it. You can call the chart builder right now like this:
```
<ChartWrapper
  id="d3-grouped-bar-chart-root"
  data={ mainChartData }
  lineNames={ [ 'failed', 'successful' ] }
  colors={ [ '#6EC664', '#A30000', '#06C' ] }
  xAxis={ {
      type: 'date',
      text: 'Date'
  } }
  yAxis={ {
      type: 'number',
      text: currentChart().yLabel
  } }
  value={ clusterTimeFrame }
  onClick={ redirectToJobExplorer }
  chart={ currentChart().chart }
  tooltip={ tooltip({
      lineNames: [ 'failed', 'successful' ],
      colors: [ '#6EC664', '#A30000' ]
  }) }
/>
```

Right now if you check this out you get the same results as originally (with less code, more configuration at call).

**What it can do**:
* can set the label text on the chart
* working on the same data set
* can pass customized tooltips

2020-08-05 11:19 UTC, Ladas commented on src/Containers/Clusters/Clusters.js
> +                              id="d3-grouped-bar-chart-root"
btw. it this is the `clusters` chart, it's called `stacked bar chart`, since we stack bars on top of each other

Will the `id` need to be unique? So we can display more of these on page?

2020-08-05 11:21 UTC, brumik commented on src/Containers/Clusters/Clusters.js
> +                              id="d3-grouped-bar-chart-root"
yeah, cannot make css recompile, if you check the code I wanted to make a `d3-chart-root` but I could not, so it will be replaced by a more proper name

2020-08-05 11:22 UTC, brumik commented on src/Containers/Clusters/Clusters.js
> +                              id="d3-grouped-bar-chart-root"
You need unique id for each ChartWrapper though, but we can make it dynamically if we can pass a class for styling with our css

2020-08-05 11:27 UTC, Ladas commented on src/Containers/Clusters/Clusters.js
> +                chart: lineChart,
btw. line chart and stacked bar chart can be under 1 component. With a `chart_type` switch, then it'll be easier to make selecbox with the type and let the user switch.

2020-08-05 11:30 UTC, brumik commented on src/Containers/Clusters/Clusters.js
> +                chart: lineChart,
It would be the same as passing a different function, and as I plan to move the other charts to this form too, I think it would just be confusing if we had `chart` prop and `chartType` prop too for some selected charts.

2020-08-05 11:44 UTC, Ladas commented on src/Containers/Clusters/Clusters.js
> +                chart: lineChart,
ok, that makes sense

2020-09-01 14:48 UTC, brumik commented
@benthomasson It should be fine I think. If the extra right border is really unwanted I can patch it, but it would introduce quite a bit of copy-paste code, so even that this is a refactor I would like to leave it like this.

2020-09-02 20:42 UTC, benthomasson requested changes
I like the general idea.  I had a few changes.

2020-09-02 20:42 UTC, benthomasson commented on src/Charts/ChartWrapper.js
> +export const ChartWrapper = props => {
Use ...args to grab the rest of the props so we can pass them to the chart function.

2020-09-03 16:39 UTC, brumik commented
@benthomasson another round? 

I didn't figured out yet how to properly test the generated chart svg.

2020-09-15 19:21 UTC, benthomasson approved these changes
This looks good now.  I like breaking out the d3 code from the rest of the react code.

2020-09-15 19:22 UTC, benthomasson commented
We should probably wait on merging this until 1.1.0 testing is done.

2020-11-02 21:24 UTC, benthomasson commented
I'm closing this pull request since we are moving to victory charts in the future and this is tied to D3.

2020-11-02 21:24 UTC, closed without merging