Job Explorer UI Cleanup
RedHatInsights/tower-analytics-frontend pull request #268
Opened 2020-09-16 20:53 UTC by jeanetteobr

This PR handles 4 TODOs from issue #238:

2. Update Pagination:
- Top of Job Explorer page should have the minimized pagination component.
- Bottom of Job Explorer page should have the default pagination component.
- Remove "Total Count" badge from the top header.

3. Update page header title to "Automation Analytics | Jobs explorer".

4. Use the compact version of the datalist component

- remove the header labels when the window size is mobile. 
- Add DataCell item labels when window size is mobile.

![Screen Shot 2020-08-17 at 3 50 31 PM](https://user-images.githubusercontent.com/32466511/90438511-129fae80-e0a2-11ea-9ee9-23e34cbf9157.png)

5. Handle long dropdown menus by setting a max-height and auto scroll.
before:
![Screen Shot 2020-08-17 at 4 05 37 PM](https://user-images.githubusercontent.com/32466511/90439586-c9505e80-e0a3-11ea-9a55-e1acd0864899.png)
after:
![Screen Shot 2020-08-17 at 4 04 31 PM](https://user-images.githubusercontent.com/32466511/90439591-cb1a2200-e0a3-11ea-8063-5a1e7719dd90.png)

2020-09-17 13:20 UTC, brumik requested changes

2020-09-17 13:20 UTC, brumik commented on src/Components/JobExplorerList.js
> +/* eslint-disable no-console */
I think this line is not needed

2020-09-17 13:20 UTC, brumik commented on src/Components/Toolbar.js
> +                        placeholderText="Filter by template"z
Trailing 'z' - accidental?

2020-09-17 13:20 UTC, brumik commented on src/Components/JobExplorerList.js
> +        <>
I think it has a wrong indent

2020-09-17 13:20 UTC, brumik commented on src/Components/JobExplorerList.js
> +    useEffect(() => {
I am not sure but I think you wanted this:
```js
    // Make a constant reference to the function
    const onResize = () => setWindowWidth(window.innerWidth);

    // On mount add event listener to update
    useEffect(() => {
        window.addEventListener('resize', onResize);

        // After unmount remove the event listener from the window.
        return () => window.removeEventListener('resize', onResize);
    }, []);
```
Maybe I am wrong but your code seems to create an event listener every time the window is resized *before* rerender (and would do it on a loop if react would actually run the code). Also, it generates console warning about not using cleanup.

2020-09-17 13:20 UTC, brumik commented on src/Components/JobExplorerList.js
> +    useEffect(() => {
See the same bellow at `JobExpolerList`

2020-09-21 19:21 UTC, jeanetteobr commented on src/Components/JobExplorerList.js
> +    useEffect(() => {
@brumik Hey, that's exactly what I was wanting. Thanks for the suggestion!

2020-09-22 06:51 UTC, brumik requested changes
Except for that one thing it is working

2020-09-22 06:51 UTC, brumik commented on src/Components/JobExplorerList.js
> +        return () => window.removeEventListener('resize', onResize());
You just need to pass the reference to the event listener
```js
        window.addEventListener('resize', onResize);
        return () => window.removeEventListener('resize', onResize);
```

This way it is called when added and when removed but not when the window is resized

2020-09-24 06:23 UTC, brumik approved these changes
LGTM

2020-09-29 20:16 UTC, merged