WIP: Hide date selectors if not filtering by date
RedHatInsights/tower-analytics-frontend pull request #270
Opened 2020-09-18 00:20 UTC by jctanner

do not render the date selectors if Date is not the current selection category

2020-09-18 13:56 UTC, jctanner commented
```
(venv) vagrant@ubuntu1804:~/keycloak_hacking/srv/tower-analytics-frontend$ fgrep -m1 -A5 -i "toolbarchip " node_modules/@patternfly/react-core/src/components/Toolbar/ToolbarFilter.tsx 
export interface ToolbarChip {
  /** A unique key to identify this chip */
  key: string;
  /** The ReactNode to display in the chip */
  node: React.ReactNode;
}
```

2020-09-18 14:21 UTC, jctanner commented
```
(venv) vagrant@ubuntu1804:~/keycloak_hacking/srv/tower-analytics-frontend$ fgrep -i -e sortby -e sortables src/Containers/JobExplorer/JobExplorer.js
 
    const [ sortBy, setSortBy ] = useState(null);
        setSortBy2,
        sortby: queryParams.sort_by ? queryParams.sort_by : null,
        setSortBy2(filters.sortby);
                        setSortBy(sort_by);
            } else if (type === 'SortBy') {
                    sortby: null
                sortby: null,
                          sortables={ sortBy }
```

2020-09-18 14:45 UTC, jctanner commented
```
(venv) vagrant@ubuntu1804:~/keycloak_hacking/srv/tower-analytics-frontend$ fgrep -i dateranges src/Containers/JobExplorer/JobExplorer.js
    const [ quickDateRanges, setQuickDateRanges ] = useState([]);
                        setQuickDateRanges(quick_date_range);
                          dateRanges={ quickDateRanges }
```

2020-09-21 06:28 UTC, brumik requested changes
I did some code nitpicking otherwise works as expected by hand testing.

2020-09-21 06:28 UTC, brumik commented on src/Components/Toolbar.js
> +    const result = item.reduce((acc, i) => {
You can return `item.reduce(...)`

2020-09-21 06:28 UTC, brumik commented on src/Components/Toolbar.js
> +        return new Array();
`return []` - you used this form before - let's stay consistent.

2020-09-21 06:28 UTC, brumik commented on src/Components/Toolbar.js
>                  val = i.value;
I am not sure if there can be multiple matching but, if there is only one can `return [i.value]`. (and maybe skip a few iterations in the process too).

2020-09-21 06:28 UTC, brumik commented on src/Components/Toolbar.js
> +            return new Array(val);
Same

2020-09-21 06:28 UTC, brumik commented on src/Components/Toolbar.js
>      return new Array();
Same

2020-09-21 06:28 UTC, brumik commented on src/Components/Toolbar.js
> +        if (sortables !== null) {
`Array.isArray(sortables)` is more bullet proof if used for `map`.

2020-09-21 06:28 UTC, brumik commented on src/Components/Toolbar.test.js
> +        const expected = new Array();
`[]`

2020-09-21 06:28 UTC, brumik commented on src/Components/Toolbar.test.js
> +        const expected = new Array();
`[]`

2020-09-22 06:24 UTC, brumik approved these changes
LGTM

2020-09-22 12:02 UTC, benthomasson approved these changes

2020-09-22 12:02 UTC, merged