Org dashboards update
RedHatInsights/tower-analytics-frontend pull request #291
Opened 2020-09-24 10:56 UTC by brumik

#240 
https://github.com/RedHatInsights/tower-analytics-backend/issues/59

* [x] Convert existing charts API to the v1
* [ ] Add hosts chart in a tab
* [ ] Decide if we display None/Null orgs (id = -2) in charts, and if yes under what name

@Ladas

2020-09-29 15:01 UTC, brumik commented
Waiting for merging, otherwise ready: https://github.com/RedHatInsights/tower-analytics-backend/issues/59

2020-09-29 20:20 UTC, kialam requested changes
We will want to reuse the filter toolbar on the org dashboards page as well. See #293 for a working first pass at that implementation. We will need to standardize how the filter toolbar gets reused on other pages.

2021-01-25 00:03 UTC, kialam requested changes
The chart seems to be rendering the dates off by one day when custom dates are selected. The response body from the API is correct so this is something on the client side.

<img width="1409" alt="Screen Shot 2021-01-24 at 6 59 16 PM" src="https://user-images.githubusercontent.com/2293210/105647944-d6ede980-5e76-11eb-9477-992271d6f16a.png">

2021-01-25 00:38 UTC, kialam requested changes
Toggling the "Ascending" and "Descending" does not seem to change the chart - I would assume that Descending would sort the data from greatest to least (aka Top 5), and Ascending would be the opposite (aka Bottom 5). Looking at the request body we are sending `id:asc` and `id:desc` and not `total_count`.

2021-01-25 00:38 UTC, kialam commented on src/Containers/OrganizationStatistics/OrganizationStatistics.js
> +    const orgsChartMapper = data => data.map(el => ({
Prefer destructuring here:

```
const orgsChartMapper = data => data.map(({ date, items }) => ({
    date: new Date(date),
    items: items.map(({ id, total_count, name }) => ({
        id,
        date: new Date(date),
        value: total_count,
        name: name ? name : 'No organization'
    }))
}));
```

2021-01-25 00:38 UTC, kialam commented on src/Containers/OrganizationStatistics/OrganizationStatistics.js
> +            setPieChart1Data(pieChartMapper(pieChart1Data, 'host_count'));
Wondering if you could change the attributes in the request body sent to `readJobRunsByOrg` and `readJobEventsByOrg` instead of calling `pieChartMapper` to map the relevant attributes that are returned?

2021-01-25 00:39 UTC, kialam commented
I would also remove the extraneous call to `dashboard_organizations` whenever `queryParams` gets updated.

2021-01-25 00:40 UTC, kialam commented
Overall, good job on this! There are a few small bugs but this is very close to being merge-able.

2021-01-25 10:13 UTC, brumik commented on src/Containers/OrganizationStatistics/OrganizationStatistics.js
> +            setPieChart1Data(pieChartMapper(pieChart1Data, 'host_count'));
I optimized the request and have the absolute minimum in the attributes (check out in `Api.js`), however here I need to map to the pie chart data format which is: `id, count, name` where the `count` in the first pie chart is `host_count` and in the second one `host_task_count`.

Maybe I did not understand what you want, but I think I cannot do that mapping in the request.

2021-01-25 11:18 UTC, brumik commented
> The chart seems to be rendering the dates off by one day when custom dates are selected. The response body from the API is correct so this is something on the client side.
> 
> <img alt="Screen Shot 2021-01-24 at 6 59 16 PM" width="1409" src="https://user-images.githubusercontent.com/2293210/105647944-d6ede980-5e76-11eb-9477-992271d6f16a.png">

I cannot reproduce this

2021-01-25 11:26 UTC, brumik commented
> I would also remove the extraneous call to `dashboard_organizations` whenever `queryParams` gets updated.

I was also commenting on your PR that we should include. There Ladas said we can put it later in another pr, so I think it's not a bad thing to leave it in for now.

2021-01-25 14:31 UTC, kialam commented
It's an extra call for a functionality that has yet to be implemented. I would remove it for now.

2021-01-25 14:31 UTC, kialam commented
re: chart dates - this could be a timezone issue.

2021-01-25 14:32 UTC, kialam commented
@jeanetteobr @benthomasson can any of you reproduce the org chart off by one day bug above?

2021-01-27 11:34 UTC, brumik commented
@kialam I parse the date as a string so it would work now, can you check out if the date problem still persists?

2021-02-04 16:28 UTC, jeanetteobr commented
@kialam @brumik Levente's fix is working. I am not longer seeing the off by one day bug. :D

2021-02-04 16:43 UTC, jeanetteobr approved these changes

2021-02-04 16:52 UTC, kialam approved these changes

2021-02-04 17:03 UTC, merged