Notifications Page UXD Audit Changes
RedHatInsights/tower-analytics-frontend pull request #321
Opened 2020-10-26 17:24 UTC by jeanetteobr

This PR handles changes to the Notifications page as noted in issue #282.

**Before:**
<img width="1790" alt="Screen Shot 2020-10-26 at 1 20 06 PM" src="https://user-images.githubusercontent.com/32466511/97205822-57c11a80-178e-11eb-88b9-622806c1aa2e.png">

**Verification:** 
![MfYqHVLLdC](https://user-images.githubusercontent.com/32466511/97205836-60195580-178e-11eb-9464-c5f232d00051.gif)

2020-10-29 13:14 UTC, brumik commented
@jeanetteobr Can you please rebase this branch? It's hard to review if there are 40+ commits that aren't related to the PR.

2020-10-29 14:05 UTC, brumik requested changes
It's great! I just did a little nitpicking and a minor change to make the code base smaller :)

2020-10-29 14:05 UTC, brumik commented on src/Components/NotificationsList.js
> +                    <NotificationDrawerListItem
Can you please extract this component into a function? It is copy-pasted basically 6 times.

I can imagine that it could be called like
```js
notifications.map(({ ... }) =>
    <CustomNotificationDrawerListItem
        variant={ getVariantFromLabel(label) }
        label={ label }
        url={ url }
        message={ message }
    />
```

2020-10-29 14:05 UTC, brumik commented on src/Containers/Notifications/Notifications.js
> +                  <NotificationDrawer>
Wrong indent for the whole `<></>` block (hm, eslint is not caching it :thinking: )

2020-10-29 14:08 UTC, brumik commented
@jo also you need to update the test, they are not passing anymore

2020-11-02 19:21 UTC, jeanetteobr commented on src/Components/NotificationsList.js
> +                    <NotificationDrawerListItem
Sounds good! Will do.

2020-11-02 20:48 UTC, jeanetteobr commented on src/Components/NotificationsList.js
> +                    <NotificationDrawerListItem
@brumik I think this work is worth capturing in a separate ticket. Abstracting out the NotificationDrawerListItem component is out of scope for this ticket.

2020-11-02 21:01 UTC, brumik commented on src/Components/NotificationsList.js
> +                    <NotificationDrawerListItem
Hm, maybe you are right, can you do it then in a followup PR? I think however it could fit into this too since you are adding (replacing) all the places it is used. (Sorry for my bad english)

2020-11-04 11:37 UTC, brumik requested changes
After console log deletion it is looking good, please remove the two lines.

2020-11-04 11:37 UTC, brumik commented on src/Components/NotificationsList.test.js
> +/* eslint-disable no-console */
delete line

2020-11-04 11:37 UTC, brumik commented on src/Components/NotificationsList.test.js
> +        console.log(wrapper.debug());
delete line

2020-11-05 17:10 UTC, jeanetteobr commented on src/Components/NotificationsList.test.js
> +        console.log(wrapper.debug());
@brumik Thanks for catching these!

2020-11-08 12:37 UTC, brumik approved these changes
I approve!

P.S.: Can you do a follow-up PR (or a `refactor` issue) for optimizing the NotificationsDrawerListItemHeader code chunks so we can get rid of a duplicated code?

2020-11-09 17:52 UTC, jeanetteobr commented
@brumik Thanks Levi! I wrote an issue that captures your ask here: https://github.com/RedHatInsights/tower-analytics-frontend/issues/335.

2020-11-09 17:53 UTC, merged