Added useApi hook to simplify fetching
RedHatInsights/tower-analytics-frontend pull request #359
Opened 2020-11-23 14:18 UTC by brumik

@kialam It was a long time ago that we speak about this, but I had to made fetching research, and while at it I come up with this solution. (Now I understand why there were `ignore` at API fetching)

I think this hook could simplify fetching API. I can fetch one endpoint or multiple (`Promise.all`). It accepts a postprocessing function, allowing it to remap or modify data from API. It is also preventing memory leaks when the component is unmounted before API is fetched.

Returns and object with the following keys: 
* (bool) isLoading
* (string) errror - null if no error
* (bool) isSuccess - loaded without error --> this variable replaces the `!isLoading && !error`, making the code more readable.
* (object) data - the loaded data from the API

**Note**: Needed to update `JobExplorerList` component to use camelCase instead of snake_case, the `useApi` hook automatically converts the fetched data to it.

cc @benthomasson

2020-12-04 14:06 UTC, brumik commented
@benthomasson Do we still need a preflight error? Can we do the preflight error check and the `auth.getUser()` in the App component itself instead of every page? (We could add a page to the `react-router` for authentication errors and that way we don't need to deal with it on all other pages.)

2020-12-08 18:52 UTC, benthomasson commented on src/Components/JobExplorerList.js
> +                                        <a href={ item.id.towerLink } target='_blank' rel='noopener noreferrer'>
Are these changes unrelated to the useApi hook?

2020-12-08 20:48 UTC, benthomasson commented
This is similar to useRequest in AWX:  https://github.com/ansible/awx/blob/5e51dd2ff7cb2db3f2b56435f47c1054bcc8b614/awx/ui_next/src/util/useRequest.js#L21

2020-12-08 22:10 UTC, benthomasson commented on src/Containers/JobExplorer/JobExplorer.js
> +        setData(readJobExplorer({ params: urlMappedQueryParams }),);
Does this line block or does it fetch the data and options in parallel?

2020-12-08 22:10 UTC, benthomasson commented on src/Containers/JobExplorer/JobExplorer.js
> +        updateURL();
If the two lines above don't block I am worried that this gets called too early.

2020-12-09 11:32 UTC, brumik commented on src/Utilities/useApi.js
> +        dispatch({ type: 'FETCH_INIT' });
Yes

2020-12-09 11:34 UTC, brumik commented on src/Utilities/useApi.js
> +                    payload: postprocess( // Apply the postprocess function.
It is optional, it gives an option to run maps or other postprocessing without needing to destructure and save the variables elsewhere (see the job explorer options which we can pass to the toolbar itself, but we need to throw out or add new keys to it)

I don't understand the second comment.

2020-12-09 11:36 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
>      }, [ queryParams ]);
It is, the function updates every time queryParam is changed and returns a new object reference. React is capable to detect it, so it can be passed to use effect.

2020-12-09 11:38 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +        setData(readJobExplorer({ params: urlMappedQueryParams }),);
Yes, it does, since the two calls are not dependent on each other, there is no problem not using `Promise.all` (which basically does the same, but waits for both of them to finish before calling the callback function)

2020-12-09 11:40 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +        setOptions(readJobExplorerOptions({ params: urlMappedQueryParams }));
I don't think we handle the option fail yet in the URL, I would say that the toolbar remains empty since it is passed there. Otherwsie the api sets the `options = { error: 'Some error', isLoading: false, isSuccess: false }` so we could do a more proper error handling if we wish.

2020-12-09 11:43 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +        updateURL();
No, `updateURL` is dependent only on the `queryParams`, we don't need the options or data to know what goes to the URL. So it could be updated before the fetching is finished.

2020-12-09 11:47 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +    /* eslint-disable-next-line */
Because `no-unused-var` rule. We are basically throwing away parts of the object. We could do it with the `delete` keyword, but it's much more verbose and much less clear.

2020-12-09 13:50 UTC, benthomasson commented on src/Containers/JobExplorer/JobExplorer.js
> +    /* eslint-disable-next-line */
Try this: https://eslint.org/docs/rules/no-unused-vars#ignorerestsiblings

2020-12-09 13:51 UTC, benthomasson commented on src/Utilities/useApi.js
> +                    payload: postprocess( // Apply the postprocess function.
I was probably wrong in the second comment now that I think about it again. So don't worry about it.

2020-12-09 13:55 UTC, benthomasson commented
@brumik If we want to make the same API call twice in a row with the same params would this be able to do that?

2020-12-09 14:02 UTC, benthomasson commented on src/Containers/JobExplorer/JobExplorer.js
> +    }, setData ] = useApi(null, { meta: {}, items: []});
The defaults values and the destructuring on the previous line are almost the same.    Is it necessary to do the rename?

2020-12-09 14:02 UTC, benthomasson commented on src/Utilities/useApi.js
> +    const [ state, dispatch ] = useReducer(dataFetchReducer, {
This is a cool way to use useReducer.

2020-12-09 14:05 UTC, brumik commented
@benthomasson
TL;DR: Yes, but forcing always feels hacky.

If `React's` shallow compare detects the change in the URL (which can be done, but feels really anti-pattern) it can refetch. It is using a `useEffect` hook internally to detect changes and refetch, so as long as it fires a `useEffect` it will refetch.

I cannot really imagine how we would force it without changing a reference that would fire a `useEffect` without this component. We are currently using `effects` as well for fetching, so it would be the same - force to fire an effect - problem as with this hook.

2020-12-09 14:07 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +    }, setData ] = useApi(null, { meta: {}, items: []});
No, this use case is more of a showcase how we can use it. (Okay, maybe yes, I am not sure, I wrote lots of tests to check if API returns an error, and for that maybe we need the destructuring part too - so ui doesn't break)

2020-12-09 14:10 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +        isSuccess,
It is redundant, but it is really simple and using a reducer so the redundancy is not painful to manage. On the other hand, we are already checking for too many variables *inline the render functions* and this variable could clean it up a little bit. 

It is more straighforward to write: `if isSuccess` than `if !loading && error === null`

2020-12-11 20:14 UTC, benthomasson requested changes

2020-12-11 20:14 UTC, benthomasson commented on src/Containers/JobExplorer/JobExplorer.js
> +    const [ options, setOptions ] = useApi(null, {}, optionsMapper);
Why do we need the initial URL?  In all examples here it is passed in as null.   Can we remove it?

2020-12-14 04:10 UTC, kialam commented
Related #376

2020-12-14 04:18 UTC, kialam commented on src/Containers/JobExplorer/JobExplorer.js
> +    }, setData ] = useApi(null, { meta: {}, items: []});
I'm having trouble figuring out how passing `null` as your initial URL calls the hook given [these lines](https://github.com/RedHatInsights/tower-analytics-frontend/pull/359/files#diff-31bc939331c6e5b934a01d1d52249903bd424c43e01a8aa64eff3613715ca286R45-R47).

2020-12-14 04:19 UTC, kialam commented on src/Containers/JobExplorer/JobExplorer.js
> +    const [ options, setOptions ] = useApi(null, {}, optionsMapper);
Same as comment above.

2020-12-14 04:23 UTC, kialam commented on src/Utilities/useApi.js
> +                        keysToCamel(
I don't understand the purpose of this helper function in this hook. IMO the parent component level should be responsible for handling the data and the fetch hook should just be responsible for passing the data returned.

2020-12-14 04:25 UTC, kialam commented on src/Utilities/useApi.js
> +                dispatch({ type: 'FETCH_FAILURE', payload: e.error });
Shouldn't you pass just `e` here? Not all API responses have an `error` attribute.

2020-12-14 04:30 UTC, kialam commented on src/Utilities/useApi.js
> +        return () => { didCancel = true; };
Yes, glad you are reusing existing logic in the code that I wrote.

2020-12-14 04:31 UTC, kialam requested changes
I would like to see this implemented on the Clusters page to see whether it simplifies fetching or not.

2020-12-14 04:35 UTC, kialam commented
@brumik how would this hook handle multiple API calls to the `job_explorer` endpoint with various different params?

2020-12-14 09:02 UTC, brumik commented on src/Utilities/useApi.js
> +                dispatch({ type: 'FETCH_FAILURE', payload: e.error });
I was not sure how the error is returned in all the cases.

2020-12-14 09:04 UTC, brumik commented on src/Utilities/useApi.js
> +                        keysToCamel(
We often do mapping in the components. We can pass the mapping function here. This would ensure that the same mapping function is used, no matter how many multiple places we query the API.

2020-12-14 09:16 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +    }, setData ] = useApi(null, { meta: {}, items: []});
Id does not fetch the API, but the variables are initialized nevertheless.

2020-12-14 09:26 UTC, brumik commented
@kialam You can create to the same endpoints as many hooks you need. Also, the hook supports promise all, so if you wish you can pass an array of endpoints and receive an array of results (However I don't think in our app there is a place where we need to synch API call returns.)

2020-12-14 13:04 UTC, brumik commented
@kialam I made the example for the clusters page, however, I get the feeling you were thinking about your PR with the v1 api right?

2020-12-14 14:04 UTC, benthomasson commented on src/Utilities/useApi.js
> +        return () => { didCancel = true; };
We should do more code sharing.  Feel free to borrow code and patterns from any open source project.  That is the main point of open source after all: learning and understanding.

2020-12-14 14:04 UTC, benthomasson commented on src/Utilities/useApi.js
> +                dispatch({ type: 'FETCH_FAILURE', payload: e.error });
I do think the error handling here needs some work.  Maybe we pass in an error handler function to useAPI with you did with `postProcess`.

2020-12-14 15:44 UTC, kialam commented on src/Containers/JobExplorer/JobExplorer.js
> +        isSuccess,
Agree with @benthomasson that this could live within the parent component level since it handles the rendering logic.

```
const isSuccess = !isLoading && !error;
```

2020-12-14 15:47 UTC, kialam commented on src/Utilities/useApi.js
> +                        keysToCamel(
The mapping should be handled on the parent component level since each child component handles the data in their own unique way. Then again, all this does is convert snake case key value pairs to camel case so we avoid lengthy eslint ignore comments so 🤷 .

2020-12-14 15:52 UTC, kialam commented on src/Utilities/useApi.js
> +            Array.isArray(url) ? url : [ url ]
Do we need this logic? None of the implementation examples pass more than one request to the hook.

2020-12-14 17:37 UTC, brumik commented on src/Utilities/useApi.js
> +            Array.isArray(url) ? url : [ url ]
I know, but I think it's nice to have an option to use the hook as Promise.all. It feels futureproof for me :D.

2020-12-14 17:37 UTC, brumik commented on src/Utilities/useApi.js
> +            Array.isArray(url) ? url : [ url ]
But I can remove it if you insist

2020-12-14 19:21 UTC, benthomasson commented on src/Utilities/useApi.js
> +                dispatch({ type: 'FETCH_FAILURE', payload: e.error });
Never mind about passing the error handler function.   It is not necessary.

2020-12-14 19:22 UTC, benthomasson commented on src/Utilities/useApi.js
> +            Array.isArray(url) ? url : [ url ]
Add one example of its use somewhere to see how it works with multiple urls.

2020-12-14 19:50 UTC, brumik commented on src/Utilities/useApi.js
> +                        keysToCamel(
@benthomasson Said he likes the idea of some kind of mapping function passed down. It is not required to use but I like the possibility too. Can save a few parent component's state destructurings.

2020-12-15 01:41 UTC, kialam commented on src/Utilities/useApi.js
> +            Array.isArray(url) ? url : [ url ]
Often what we think of "futureproofing" is just needless abstraction/complication. How does your `postprocess` handle mapping of data from multiple asynchronous sources?

2020-12-15 01:53 UTC, kialam commented
A lot of this uses `useReducer` to return an object from `useAPI` hook. I can also see a much more simplified version of this without the `useReducer` hook:

```
import { useState, useEffect } from 'react';

const useApi = (request) => {
	const [ res, setRes ] = useState([]);
	const [ isLoadinig, setIsLoading ] = useState(true);
	const [ error, setError ] = useState(null);

    useEffect(() => {
        // Initialize
        let didCancel = false;
		
        // Fetching
        window.insights.chrome.auth.getUser().then(() => Promise.all(
            [ request ]
        ).then(data => {
            if (!didCancel) {
            	// post process here if you want
                setRes(data);
            }
        }).catch(e => {
            if (!didCancel) {
                setErrorr(e);
            }
        })).finally(() => {
        	setIsLoadiing(false);
        });

        return () => { didCancel = true; };
    }, []);

    return {
        resp,
        isLoading,
        error
    };;
};

export default useApi;
```

2020-12-15 10:31 UTC, brumik commented on src/Utilities/useApi.js
> +            Array.isArray(url) ? url : [ url ]
Well, the data is passed to the postprocess as we get it in the promise all, so if we know that we are passing an array of urls to the hook then we await an array of objects as a result. So the postprocess accepts an array of objects as an argument and works with them.

2020-12-15 10:45 UTC, brumik commented
> A lot of this uses `useReducer` to return an object from `useAPI` hook. I can also see a much more simplified version of this without the `useReducer` hook:
> 
> ```
> import { useState, useEffect } from 'react';
> 
> const useApi = (request) => {
> 	const [ res, setRes ] = useState([]);
> 	const [ isLoadinig, setIsLoading ] = useState(true);
> 	const [ error, setError ] = useState(null);
> 
>     useEffect(() => {
>         // Initialize
>         let didCancel = false;
> 		
>         // Fetching
>         window.insights.chrome.auth.getUser().then(() => Promise.all(
>             [ request ]
>         ).then(data => {
>             if (!didCancel) {
>             	// post process here if you want
>                 setRes(data);
>             }
>         }).catch(e => {
>             if (!didCancel) {
>                 setErrorr(e);
>             }
>         })).finally(() => {
>         	setIsLoadiing(false);
>         });
> 
>         return () => { didCancel = true; };
>     }, []);
> 
>     return {
>         resp,
>         isLoading,
>         error
>     };;
> };
> 
> export default useApi;
> ```

I don't see why is this "simpler", expect that this is rather a helper function than a hook (this solution doesn't expose URL change and probably would operate on calling the function every time when we want to fetch the data).

I favored reducer in this case because you can see much clearer in the reducer which action how affects the different states in one place. The loading, error, success, and data states we look at as basically one object. Reducers are great for these situations in my opinion. This is why I decided to have the `isSuccess` in because it is so easy to see if I made a mistake in the reducer.

2020-12-15 10:49 UTC, brumik commented on src/Utilities/useApi.js
> +                        keysToCamel(
And it is still done in the parent, you have to define the function in the parent.

2020-12-15 22:51 UTC, kialam commented on src/Containers/JobExplorer/JobExplorer.js
>      }, [ queryParams ]);
Frankly `urlMappedQueryParams` adds unnecessary obfuscation in its usage and implementation. The snake to camel conversion should happen at the API level (Api.js) rather than being sprinkled everywhere in the code.

2020-12-15 22:59 UTC, kialam commented on src/Utilities/useApi.js
> +                dispatch({ type: 'FETCH_FAILURE', payload: e.error });
v1 API returns a `details` object for any errors returned.

2020-12-15 23:04 UTC, kialam commented on src/Containers/JobExplorer/JobExplorer.js
> +        updateURL();
We shouldn't be using `updateURL` at all.

2020-12-15 23:07 UTC, kialam commented
We do not have parameterized URLs in our other views so how would this hook work?

2020-12-16 11:06 UTC, benthomasson approved these changes

2021-01-06 13:23 UTC, brumik commented
@benthomasson @kialam Should I finish up this hook?
We need to remove keys to the camel function from it and resolve conflicts.

I would delete the usage on the Clusters page since @kialam works on that page anyway. Then @kialam could rebase and use the hook

2021-01-25 23:47 UTC, kialam commented
@brumik let's try and merge this PR this week so we can start using it. Nice work 👍

2021-01-27 16:39 UTC, kialam approved these changes

2021-01-27 16:40 UTC, merged