Convert Clusters view to V1 API
RedHatInsights/tower-analytics-frontend pull request #364
Opened 2020-12-01 15:47 UTC by kialam

This PR converts the Clusters view to use the V1 `job_explorer` and `event_explorer` endpoints.

![Screen Shot 2020-11-30 at 12 34 50 PM](https://user-images.githubusercontent.com/2293210/100762996-a2076e00-33c2-11eb-8dab-59f02368b498.png)

2020-12-04 13:53 UTC, brumik reviewed
I came here to see what I need to use for the Org toolbar, but here is a tip: (I know this is a WIP)

2020-12-04 13:53 UTC, brumik commented on src/Containers/Clusters/Clusters.js
> +                        cluster_id,
You can make these lines much more compact, like here:

https://github.com/RedHatInsights/tower-analytics-frontend/blob/ff81a72308f9fd5b5aca5c46c501e2a1ae2fbfa5/src/Containers/OrganizationStatistics/OrganizationStatistics.js#L128

```js
    useEffect(() => {
        ...
        window.insights.chrome.auth.getUser().then(() => Promise.all(
            [
                readJobExplorerOptions({ params: urlMappedQueryParams }),
                ...
            ]
        ).then(([
            options, // Don't destructure, we eventually want to be this object the default settings for the toolbar probably
            ...
        ]) => {
         
            /* eslint-disable-next-line */ // Exlude options which you don't want to display
            const { sortBy, groupBy, attributes, ...rest } = keysToCamel(options);

           // Add extra options, set ONE state
            setOptions({ ...rest, sortBy: constants.sortBy });
            ...
        })

```

2020-12-04 13:53 UTC, brumik commented on src/Containers/Clusters/Clusters.js
> +                    categories={ {
Then you can do simething like this with the options:
```js
<FilterableToolbar
    categories={ options }
    filters={ queryParams }
    setFilters={ setFromToolbar }
/>
```

2020-12-04 13:53 UTC, brumik commented on src/Containers/Clusters/Clusters.js
> +                    readJobExplorer({ params: urlMappedQueryParams(queryParams) }),
Fetching the same data in the `mounting` effect and the `queryParam` effect doesn't fetch it twice when mounted?

Anyway, I think having the same functionality in the code as a duplicate is not too nice. So maybe we can have API calls which we need only load once in the mount and the others in their effect? So when we need to change something on the call we don't need to change it in two places.

2020-12-04 21:15 UTC, kialam commented on src/Containers/Clusters/Clusters.js
> +                    readJobExplorer({ params: urlMappedQueryParams(queryParams) }),
Yes thanks for catching this. I had some logic around `firstRender` that would skip the queryParams useEffect hook entirely and it must have gotten lost during one of my rebases. I've now added it back :).

2020-12-05 07:38 UTC, brumik commented on src/Containers/Clusters/Clusters.js
> +                    readJobExplorer({ params: urlMappedQueryParams(queryParams) }),
If you are taking this approach (fetching in multiple places the same), I am pretty sure you don't need a `state` for `firstRender`, simple `let firstRenderd` is enough, since you don't need to tell react to rerender stuff.

2020-12-30 16:45 UTC, kialam commented on src/Containers/Clusters/Clusters.js
> +                    readJobExplorer({ params: urlMappedQueryParams(queryParams) }),
I have found that using a simple variable declaration and initialization (e.g. `let firstRender = true`) will not work. The variable gets added to the lexical environment and is assigned its initial value each time the component gets rendered. Since we have a hook that updates our component whenever `queryParams` gets updated, `firstRender` needs to be a state variable.

2020-12-31 10:24 UTC, brumik commented on src/Containers/Clusters/Clusters.js
> +                    readJobExplorer({ params: urlMappedQueryParams(queryParams) }),
Oh, sorry for the misleading info. Thanks for the explanation.

Wouldn't it be easier to fetch the `chart30, modules, templates` only in the `queryParam` effect and avoid all `firstRender` logic? I know that `mount` effect takes precedence on the other effects, but we have only an async call, so I don't think it is delaying render by much.

Is there also some performance reason that there is double code for fetching of some endpoints? (chart30, modules, templates in the mount and in the queryParam use effect)

2020-12-31 21:15 UTC, kialam commented on src/Containers/Clusters/Clusters.js
> +                    readJobExplorer({ params: urlMappedQueryParams(queryParams) }),
The queryParam hook handles updating data for the chart, top templates, top workflow, and top modules portion of that page. The hook that fetches on mount gets the initial data for those sections, as well as making additional calls to the `dashboard_clusters_options` and `authorized` endpoint. This optimizes performances by limiting the amount of API calls we make based on various parameters changing to the ones we need.

2021-01-04 15:56 UTC, kialam commented
@Ladas should the `total_count` for the "Top Templates" or "Top Workflows" list also match the `total_count` attribute for the top templates/top workflows detail modal?

Eg:
![Screen Shot 2021-01-04 at 10 52 52 AM](https://user-images.githubusercontent.com/2293210/103553135-05316800-4e7b-11eb-9544-b97c1bf86b76.png)
![Screen Shot 2021-01-04 at 10 52 44 AM](https://user-images.githubusercontent.com/2293210/103553136-05316800-4e7b-11eb-9617-77488e82ea24.png)

The current request payloads are as following:

(Top Templates/Workflows list)
```
{"quick_date_range":"last_30_days","group_by":"template","limit":10,"job_type":["workflowjob"],"group_by_time":false}
```

Detail Modal:
```
{"group_by":"template","template_id":[2],"attributes":["elapsed","job_type","successful_count","failed_count","total_count","most_failed_tasks","most_failed_steps"],"status":["successful","failed"],"quick_date_range":"last_30_days","job_type":["workflowjob"]}
```
Sidenote: most_failed_step percentage seems off. I will look into this.

2021-01-04 16:43 UTC, Ladas commented
@kialam yeah the counts should match. I see that the detail modal gets extra status filter? That is probably why the numbers don't match

2021-01-04 16:47 UTC, Ladas commented
@kialam can you print here the body for most failed step? It should be normalized to 100% from what I remember (because the test data has the same template in workflow multiple times I think, so the step can fail more times than the workflow)

2021-01-04 17:21 UTC, kialam commented
@Ladas yep, here's the response body:

```
failed_count: 100
failed_host_count: 3525900
host_count: 366693600
job_type: "job"
passed_host_count: 356115900
template_id: 2
template_name: "template_name_0"
total_canceled_count: 0
total_error_count: 0
total_failed_count: 10
total_failed_host_count: 20
total_host_count: 2080
total_successful_count: 12
total_unfinished_count: 0
total_unreachable_host_count: 40
unreachable_host_count: 7051800
```

2021-01-04 17:31 UTC, Ladas commented
@kialam hm, there is something fishy in there, saying the step ran on 366M hosts (might explain why the query is so slow)

It's saying the step template_name_0 (nested template or workflow) failed 100 times, but it only cause 10 failures of the parent workflow. (so this step failed 10 times in each worflow)

I'll need to look into why the dedup is not working (it should be showing unique template failing the top workflow, so it should say it failed 10 times, if it failed in all workflows)

2021-01-22 12:20 UTC, brumik requested changes
Removing the template filter or org filter does as incorrect querry:
![Screenshot from 2021-01-22 13-18-40](https://user-images.githubusercontent.com/8531681/105490081-8890ed00-5cb4-11eb-93d2-3f048e4e5a9c.png)

2021-01-22 12:46 UTC, brumik requested changes
Its a nice work, I had mostly nitpicking and code format in the review.

Howver there is one issue (which may be connected to the API - I am using up to date devel backend) where a top module has no name. Maybe we can write `No module name` or something when there is no name?

![Screenshot from 2021-01-22 13-44-40](https://user-images.githubusercontent.com/8531681/105492456-436eba00-5cb8-11eb-8226-b1552314b388.png)

@Ladas

2021-01-22 12:46 UTC, brumik commented on src/Charts/BarChart.js
> +            orgId
I think the previous problem may be caused by these lines: (not sure) but it seems we should pass:
```js
...
template_id: templateId,
org_id: org_id
```

2021-01-22 12:46 UTC, brumik commented on src/Charts/LineChart.js
> +            templateId
If the previous one is causing problems, probably this one will too

2021-01-22 12:46 UTC, brumik commented on src/Charts/LineChart.js
> +          ')'
Indent

2021-01-22 12:46 UTC, brumik commented on src/Charts/LineChart.js
> +    history: PropTypes.object
**Just a note**: You can pull history from the `react-router` as an import and remove `withRouter` import and it would make the charts testing easier (for one) and then there is no need to pass history.

(I remember doing this some time ago)

2021-01-22 12:46 UTC, brumik commented on src/Components/TemplatesList.js
> +        return () => (ignore = true);
Can we use `didCancel` here too for consistency?

2021-01-22 12:46 UTC, brumik commented on src/Containers/Clusters/Clusters.js
> +        return () => (ignore = true);
Oh sorry, I thought you changed these to `didCancel` that's why the comment ^

2021-01-22 12:46 UTC, brumik commented on src/Containers/Clusters/Clusters.js
> +            readClustersOptions({ params: optionsQueryParams }).then(
I was talking with @Ladas and I think we will need to refetch these too on queryParam change since in the future options like `granularity` will change the `quick date ranges` and possibly other options too.

So I think it would be futureproofing if we would do the refetching of the options too when changing values instead of fetching once on mount.

@Ladas Correct me if I am wrong.

2021-01-22 12:46 UTC, brumik commented on src/Containers/Clusters/Clusters.js
>          <>
Can we use `React.Fragment` instead of the sorthand. The shorthand messes up the Eslint indent rules.

2021-01-22 12:56 UTC, Ladas commented on src/Containers/Clusters/Clusters.js
> +            readClustersOptions({ params: optionsQueryParams }).then(
@brumik yeah, but we can do this in separate PR. Also we should get together with @AparnaKarve and see how to enable `show only eligible options`, where filtering always produces some results. 

So e.g. from start you can filter 10 templates and 10 orgs, you'll filter 2 orgs and now you can see only 5 templates (since only 5 templates are being used by those 2 orgs).

We'll need to design together how this should work.

2021-01-22 14:38 UTC, Ladas commented
> Its a nice work, I had mostly nitpicking and code format in the review.
> 
> Howver there is one issue (which may be connected to the API - I am using up to date devel backend) where a top module has no name. Maybe we can write `No module name` or something when there is no name?
> 
> ![Screenshot from 2021-01-22 13-44-40](https://user-images.githubusercontent.com/8531681/105492456-436eba00-5cb8-11eb-8226-b1552314b388.png)
> 
> @Ladas

@kialam @brumik the empty module name shouldn't appear in prod data. But later I'd be just for some generic empty name decorator we'd use everywhere?

2021-01-25 14:34 UTC, kialam commented on src/Containers/Clusters/Clusters.js
> +            readClustersOptions({ params: optionsQueryParams }).then(
Until there is an API implementation of this, I will not be changing the UI to include extra calls.

2021-01-27 10:46 UTC, Ladas commented on src/Containers/Clusters/Clusters.js
> +            readClustersOptions({ params: optionsQueryParams }).then(
yeah, it can wait until it's needed

2021-02-02 23:36 UTC, kialam commented
@brumik after using the `useAPI` hook for `TemplatesList`, I am seeing this error in the console when the modal gets closed:

![Screen Shot 2021-02-02 at 5 46 27 PM](https://user-images.githubusercontent.com/2293210/106676758-7a30b400-6585-11eb-8116-ca0683a9de68.png)

2021-02-03 11:21 UTC, brumik commented
@kialam Can you show me? It is really vague like this (you didn't push the non-working version it seems)

2021-02-03 15:05 UTC, kialam commented on src/Components/TemplatesList.js
> +                    setRelatedJobs([]);
@brumik using the returned `setState` from `useAPI` here fails with a `request.then is not found` error message. The hook expects the `setState` method to be called with a request, however I am using it to reset to the initial state of `[]`.

2021-02-03 16:48 UTC, brumik commented on src/Components/TemplatesList.js
> +                            setRelatedJobs([]);
@kialam Oh yes, you cannot do that now. The `setRequest` expects a `Promise` returned. Right now you cannot reset the state. However, if you remember yesterday's conversation, this is solved here: https://github.com/RedHatInsights/tower-analytics-frontend/pull/323/commits/01b7b6f4928aa3619e823bf1324cd79ab1d4ddbe#diff-31bc939331c6e5b934a01d1d52249903bd424c43e01a8aa64eff3613715ca286

Then you can use the `setData` function instead of `setRequest` from the `useApi` hook. I had a different use case for this change but this is a perfectly valid one.

2021-02-04 12:37 UTC, brumik commented on src/Charts/BarChart.js
> +        const data = unformattedData.reduce((formatted, { created_date, successful_count, failed_count }) => {
I know this is a "legacy" code but these two lines could be simplified as:
```js
const data = this.props.data.map(({ created_date, successful_count, failed_count, ...rest }) => (
    ...rest,
    DATE: parseTime(created_date) || new Date(),
    RAN: +successful_count || 0,
    FAIL: +failed_count || 0,
    TOTAL: +successful_count + failed_count || 0
));

In the current code there are too much variables and most of them is not even `constant`
```

2021-02-04 12:38 UTC, brumik commented on src/Charts/LineChart.js
> -        const data = unformattedData.reduce((formatted, { created, successful, failed }) => {
The previous comment could be applied here too

2021-02-04 12:51 UTC, brumik commented on src/Components/TemplatesList.js
>      }, [ selectedId ]);
@kialam I was thinking about this: could we fetch the data in the modal where it is used?

So what I am thinking:
* On button/link click -> open modal (`setIsModalOpen(true)`)
* Modal would have a React Component `X`  as a child with the `selectedID` param
* The `X` would on mount parse the data from the API with its own loading screen, API error, etc...

This hierarchy would make the `TemplateList` component smaller and would move the parsing logic where it is used for the modal component. Also, you would not need to reset the modal component data on close because on open it would display the `loading` screen not the old data. 

I hope I could explain it well, if not ping me

2021-02-04 16:16 UTC, kialam commented on src/Charts/LineChart.js
> +    history: PropTypes.object
https://reactrouter.com/web/api/Hooks/usehistory :)

2021-02-05 01:57 UTC, kialam commented on src/Containers/Clusters/Clusters.js
>          <>
I think this is an issue with our linter.

2021-02-05 12:13 UTC, brumik approved these changes
Great work, it is really extensive, I had a few nitpicks, but nothing that is blocking this PR to get merged. If you want you can change them, if not, this is good to be merged.

Additionally discovered another issue with the Toolbar's `Clear All Filter` but I believe that issue is not specific to this PR and I will fix it in a different PR.

2021-02-05 12:13 UTC, brumik commented on src/Components/ModalContents.js
> +    <>
Can we use <React.Fragment> to help eslint?

2021-02-05 12:13 UTC, brumik commented on src/Components/ModalContents.js
> +            { /* <ModalContents selectedId={ selectedId } qp={ qp } jobType={ jobType } /> */ }
Forgot to delete?

2021-02-05 12:13 UTC, brumik commented on src/Components/Toolbar/ToolbarFilterItem.js
> +            data-cy = { categoryKey }
Nice ^^

2021-02-05 12:13 UTC, brumik commented on src/Containers/Clusters/Clusters.js
> +        const fetchEndpoints = () => {
No need for extra function here

2021-02-05 12:13 UTC, brumik commented on src/Containers/Clusters/Clusters.js
>          <>
This is why I try to use `React.Fragment` instead of the shorthand, eslint doesn't detect indent mismatch

2021-02-05 14:29 UTC, merged