useFetch hook POC
RedHatInsights/tower-analytics-frontend pull request #375
Opened 2020-12-14 04:06 UTC by kialam

Borrows AWX's [useRequest](https://github.com/ansible/awx/blob/devel/awx/ui_next/src/util/useRequest.js) hook to create an AA useFetch hook.

Usage:

```
const {
        result: { jobExplorerData, meta },
        error: jobsError,
        isLoading: isJobExplorerLoading,
        request: fetchJobExplorer
    } = useFetch(
        useCallback(async params => {
            const [ jobs ] = await Promise.all([ readJobExplorer({ params }) ]);
            return {
                jobExplorerData: jobs.items,
                meta: jobs.meta
            };
        }, []),
        {
            jobExplorerData: [],
            meta: {}
        }
    );
```
- destructure & and reassign the object that this hook returns:
```
{
   result::any,
   error::any,
   isLoading::boolean,
   request::function
}
```

- pass function as first argument to hook. This function is a [callback hook](https://reactjs.org/docs/hooks-reference.html#usecallback) that is referenced as `makeRequest` and is expected to return an object.

```
useCallback(async params => {
    const [ jobs ] = await Promise.all([ readJobExplorer({ params }) ]);
    return {
        jobExplorerData: jobs.items,
        meta: jobs.meta
    };
}, []),
```

- second argument is the initial default values of your result(s)

```
{
    jobExplorerData: [],
    meta: {}
}
```

Lastly use it like you would within a regular `useEffect` hook:

```
useEffect(() => {
    fetchJobExplorer(urlMappedQueryParams);
}, [ queryParams ]);
```

Question:
1. Should `preFlight request` be called before each API request or just once when component mounts?

2020-12-14 04:10 UTC, kialam commented
Related #376

2020-12-14 09:59 UTC, brumik requested changes
This is very similar in the use case to the other PR. It is utilizing a lot of memoization, which is nice since it allows to pass initial URL when calling the hook without firing the hook multiple times.

2020-12-14 09:59 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> -    const updateURL = () => {
We don't need this anymore?

2020-12-14 09:59 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +    // const [ preflightError, setPreFlightError ] = useState(null);
We don't need preflight check anymore? I don't see it moved and I am a bit puzzled

2020-12-14 09:59 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +              jobExplorerData.length > 0 && (
Indent mismatch.

Also, I don't see why we need to wait **here** for job explorer options to load? We could indicate it in the toolbar or if we need the data and the options to synch maybe we can use Promise.all to fetch them.

2020-12-14 09:59 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +    }, [ fetchJobExplorerOptions ]);
Maybe this is just for showcasing the options of usage?

I guess this is needed in case of the `useCallback` reference changes when the `urlMappedQueryParams` change. However then why we cannot do it for the `fetchJobExplorer` too?

Personally, I think this is a bit less readable than having them both be called in the `useEffect` with `queryParams`.

2020-12-14 14:54 UTC, benthomasson commented
@keithjgrant wrote useRequest.

2020-12-14 14:56 UTC, benthomasson commented on src/Containers/JobExplorer/JobExplorer.js
> +        useCallback(async params => {
It seems like useCallback is always used with useFetch.  Can it be added to useFetch so we don't need the boilerplate code?

2020-12-14 15:14 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +              jobExplorerData.length > 0 && (
I am not sure how indicating loading and parallel data loading is connected?

2020-12-14 15:32 UTC, kialam commented on src/Containers/JobExplorer/JobExplorer.js
> +    }, [ fetchJobExplorerOptions ]);
The job explorer options should only be fetched once when the toolbar component renders.

2020-12-14 15:34 UTC, kialam commented on src/Containers/JobExplorer/JobExplorer.js
> -    const updateURL = () => {
I think we can remove this since bookmarking is not yet implemented. Leftover code.

2020-12-14 15:35 UTC, kialam commented on src/Containers/JobExplorer/JobExplorer.js
> +    // const [ preflightError, setPreFlightError ] = useState(null);
I commented it out because I am not sure the order/prioritization of this call within the new hook. If it can only be called once on initial render then we can pass it like we do to the hook, however if it needs to be called for each call then it needs to be incorporated in the hook itself. @benthomasson thoughts on this?

2020-12-14 15:38 UTC, kialam commented on src/Containers/JobExplorer/JobExplorer.js
> +              jobExplorerData.length > 0 && (
So, this conditional ensures that there are no errors returned from the API before we render the jobs list. @brumik yeah any errors from the options endpoint should be moved to the filter toolbar block.

2020-12-14 15:40 UTC, kialam commented on src/Containers/JobExplorer/JobExplorer.js
> +        useCallback(async params => {
@benthomasson I am not sure I understand what you mean here...

2020-12-14 16:43 UTC, keithjgrant commented on src/Containers/JobExplorer/JobExplorer.js
> +        useCallback(async params => {
We tried to find a way to push `useCallback` down in AWX and ultimately decided against it. Primarily, it breaks linting, since the React hooks lint tools need to see the dependency array defined inline where `useCallback` is invoked (i.e. you can't pass the whole dependency array in as a parameter without linting errors). It would also basically go against the purpose of useCallback, which is to make a callback hooks-safe at the point where you define it.

2020-12-14 17:31 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +    }, [ fetchJobExplorerOptions ]);
Hm, okay, when we were talking about before I got the feeling that the options endpoint can return different values depending on the current options too (like changing in the future granularity would change date selection options).

2020-12-14 17:33 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> -    const updateURL = () => {
Actually, bookmarking is working for JobExplorer right now with this code

2021-01-27 14:31 UTC, brumik commented
Closing in favour of https://github.com/RedHatInsights/tower-analytics-frontend/pull/359
@kialam delete the branch if you you also think we won't need this anymore

2021-01-27 14:31 UTC, closed without merging