[WIP] evert keystocamel
RedHatInsights/tower-analytics-frontend pull request #383
Opened 2020-12-16 12:09 UTC by benthomasson

2020-12-17 15:04 UTC, kialam approved these changes

2020-12-17 15:45 UTC, brumik requested changes
This breaks the toolbar. If you try it out you will see that toolbar is unable to display values and send changes and nothing loads what is hooked up to the toolbar. The toolbar operated on the camel cased variables and options. If we need to remake the query params to camel case we need to remake most of the toolbar too.

2020-12-17 15:46 UTC, brumik commented
![Screenshot from 2020-12-17 16-45-51](https://user-images.githubusercontent.com/8531681/102509899-5e318b80-4087-11eb-8ba1-cd1a90d01187.png)

2020-12-17 15:56 UTC, kialam commented
@brumik check your db - it may not have past 30 days worth of data to show.

2020-12-17 16:10 UTC, kialam requested changes
Toolbar dropdown UI needs minor fix:
![Screen Shot 2020-12-17 at 11 30 52 AM](https://user-images.githubusercontent.com/2293210/102535662-82d13780-4076-11eb-8b55-820b3cf21b55.png)

2020-12-17 16:16 UTC, brumik commented
I have data, and it works on devel

2021-01-04 16:37 UTC, jctanner approved these changes

2021-01-05 17:00 UTC, jctanner commented on src/Utilities/useQueryParams.test.js
> +        const currentDate = moment(new Date().toISOString()).format('YYYY-MM-DD');
:+1:

2021-01-05 17:00 UTC, jctanner commented on src/Utilities/useQueryParams.test.js
> +        const currentDate = moment(new Date().toISOString()).format('YYYY-MM-DD');
:+1:

2021-01-05 17:04 UTC, jctanner commented on src/Utilities/useQueryParams.test.js
> +        const expected = moment(date.toISOString()).format('YYYY-MM-DD');
:+1:

2021-01-06 13:11 UTC, brumik requested changes
I think these JobExplorer API fetching changes are a bit off the scope of this PR. I made some request around the API loading, which we discussed earlier this week.

2021-01-06 13:11 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +        if (!isFirstRender) {
Can we revert this not to use the `isFirstRender` logic?

2021-01-06 13:11 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +        const update = async () => {
Missing guard `didCancel`

2021-01-06 13:11 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> +        let ignore = false;
Can we call this variable `didCancel`? For me it explains more than `ignore` (it kinda answers the question: why we ignore saving)

2021-01-07 14:46 UTC, kialam approved these changes

2021-01-07 15:03 UTC, brumik approved these changes

2021-01-07 19:58 UTC, merged