Broken cypress tests into smaller per page files
RedHatInsights/tower-analytics-frontend pull request #393
Opened 2021-01-18 18:46 UTC by brumik

2021-01-18 18:48 UTC, brumik commented
@kialam Look at this and try to run the tests, I removed from notification and orgs the waits, if it runs with you locally and on github I remove the other waits as well, as it is an antipattern.

2021-01-18 19:53 UTC, kialam requested changes
I can't seem to get the other test files to run although it looks like AutomationCalculator.spec.js runs fine. I would test these changes against prod before moving forward with removing the wait calls.

2021-01-18 19:53 UTC, kialam commented on package.json
> +    "integration_headless": "cypress run --headless --browser chrome --spec 'cypress/integration/*.spec.js'",
No need to pass the `--spec` flag. The cypress runner will know to look in the `/integration` directory. `cypress run --headless --browser chrome` should work.

2021-01-18 19:53 UTC, kialam commented on cypress.json
> +    "env": {
Leave out CLOUD_BASE_URL, CLOUD_USERNAME, and CLOUD_PASSWORD as it can differ from machine to machine or based on what you want to point cypress at.

2021-01-18 19:53 UTC, kialam commented on cypress/integration/AutomationCalculator.spec.js
> +describe('Notification page smoketests', () => {
Automation Calculator not Notification

2021-01-19 11:21 UTC, brumik commented on cypress.json
> +    "env": {
You can override them if you define them in the terminal:
https://docs.cypress.io/guides/guides/environment-variables.html#Setting
So this is the same as was before, a default value if you don't define them.

2021-01-20 11:26 UTC, brumik commented
@kialam I put the wait back, now we need to figure out where the package.json config is coming to the github action (docker image).

2021-01-20 15:17 UTC, kialam approved these changes

2021-01-20 15:17 UTC, merged