'View All' Bugfix on Notifications page
RedHatInsights/tower-analytics-frontend pull request #395
Opened 2021-01-25 22:40 UTC by jeanetteobr

### Verification
This PR addresses a bug in prod on the Notifications page that causes an empty query string to be sent to the Notifications endpoint on the selection of the 'View All' filter. 

**Before:**
![DMG1fsE3SY](https://user-images.githubusercontent.com/32466511/105775018-18909a00-5f34-11eb-95c8-9cc77dd0ddf0.gif)

**After:**
![GFE0niCKt2](https://user-images.githubusercontent.com/32466511/105774988-057dca00-5f34-11eb-90de-493142b86653.gif)

Jira Issue: https://issues.redhat.com/browse/AA-238

2021-01-26 12:45 UTC, brumik requested changes

2021-01-26 12:45 UTC, brumik commented on src/Utilities/useQueryParams.js
> +                if (value.severity === '') {
You cannot do this, this way you break the `SET_OFFSET` rule here.

2021-01-26 12:45 UTC, brumik commented on src/Utilities/useQueryParams.js
> +                    const { severity: ignored, ...rest } = state;
We don't need `ignored` anymore, there was a rule added in eslint for destructuring + unused

2021-01-26 12:45 UTC, brumik commented on src/Utilities/useQueryParams.js
> +        setSeverity: (severity) => {
I think here no functionality changed except not returning the dispatch return value?

2021-01-26 12:45 UTC, brumik commented on src/Utilities/useQueryParams.js
> +/* eslint-disable no-console */
Forgot eslint rule

2021-01-26 15:01 UTC, brumik commented
@kialam I remember when we could break this: when we were converting maybe from `urlMappedQueryParams` to `queryParams` only. Since in the `urlMappedQuerryParams` I was removing the empty params :thinking:

2021-01-26 16:14 UTC, jeanetteobr commented on src/Utilities/useQueryParams.js
> +                if (value.severity === '') {
Could you please elaborate on how the logic on line 32 would break the `SET_OFFSET` rule?

2021-01-26 16:15 UTC, jeanetteobr commented on src/Utilities/useQueryParams.js
> +                    const { severity: ignored, ...rest } = state;
We are doing something similar on line 21 with `SET_LIMIT`...

2021-01-26 16:17 UTC, jeanetteobr commented on src/Utilities/useQueryParams.js
> +        setSeverity: (severity) => {
I was console logging some values here and neglected to revert the function to its original state...

2021-01-26 17:54 UTC, brumik commented on src/Utilities/useQueryParams.js
> +                    const { severity: ignored, ...rest } = state;
Yes, it was needed before, but we changed the eslint rules a week or two back, so now we don't need it

2021-01-26 17:59 UTC, brumik commented on src/Utilities/useQueryParams.js
> +                if (value.severity === '') {
Hm, hard to explain for me so sorry if it baroquesq:

When you write a list of cases then it will jump off the only on break or return from the switch block. So in this example right now from `SET_OFFSET` to `SET_ROOT_WORKFLOWS_AND_JOBS` were using the same line of code: `return { ...state, ...value };` since there were no other `return` or `break` statements.

Now you modified it sonow the `SET_OFFSET` which is before `SET_SEVERITY` uses the logic what you wrote for `SET_SEVERITY`. 

So basically if there is no break or return after a case the next case code is also run. 

So for example you can (and maybe should) delete your `return { ...state, ...value };` line and just leave the `if` block, since you won't have any return so the last `return { ...state, ...value };` would run.

2021-01-26 18:01 UTC, brumik commented on src/Utilities/useQueryParams.js
> +                if (value.severity === '') {
So, yeah, I didn't tested the code and it may work, but it is not safe to leave it like this I think. My solution would be to move the `SET_SEVERITY` case block under `SET_ROOT_WORKLOFS_AND_JOBS` code block.

2021-01-26 18:01 UTC, brumik commented on src/Utilities/useQueryParams.js
> +                if (value.severity === '') {
And sorry that I didn't explain it before, it was a mistake I made in a hurry.

2021-01-26 18:04 UTC, brumik commented on src/Utilities/useQueryParams.js
> +                    const { severity: ignored, ...rest } = state;
It's not actually is a problem, I just don't like extra character typing :D but you can leave it

2021-01-28 16:38 UTC, brumik approved these changes
I approve, the bug is gone!

2021-01-28 16:43 UTC, brumik commented
I guess we need to test the `queryParam` hook better in jest, if you want to try you can look for my `useApi.test.js` where I test a hook. It's pretty simple :) But that is outside of the scope of PR so this is good to go

2021-02-03 15:11 UTC, merged