Expanded filter dropdown bugfix
RedHatInsights/tower-analytics-frontend pull request #405
Opened 2021-02-09 18:23 UTC by jeanetteobr

This PR fixes a bug that causes filter dropdowns to go off-page when there are several options. 

### Verification 

**Before**
![Screen Shot 2021-02-09 at 1 16 30 PM](https://user-images.githubusercontent.com/32466511/107408963-a4302c00-6ad9-11eb-9398-4c91de871375.png)

**Fixed**
![Screen Shot 2021-02-09 at 1 12 53 PM](https://user-images.githubusercontent.com/32466511/107408980-a98d7680-6ad9-11eb-8153-7f71675ac3d4.png)

2021-02-10 11:30 UTC, brumik approved these changes
:+1:

2021-02-10 14:21 UTC, kialam requested changes
We need to add fix for when the dropdown is too wide as well. If you visit the Clusters page on CI/Beta and select the Clusters dropdown, you can see where the dropdown takes up more than half the width of the page.

2021-02-10 14:40 UTC, kialam reviewed
Another way to approach this is to leverage the css variables already provided to us by PF:

```
overflow: auto;
max-height: calc(var(--pf-c-select__menu-item--LineHeight) * var(--pf-c-select__menu-item--FontSize) * 15);
```
^^ will give us 10 menu items

2021-02-10 16:47 UTC, kialam commented
@jeanetteobr I am going to leave this up to you to include the fix for the wide select dropdown as part of this PR or a new one. Just didn't want the issue to be forgotten. I'll approve this if it's ready to go.

2021-02-10 16:47 UTC, kialam approved these changes

2021-02-10 20:09 UTC, jeanetteobr commented
@kialam @brumik  I would like to include the fix for the wide expanded menu in this PR as well. I'm working on it now. Thanks!

2021-02-11 08:58 UTC, brumik requested changes
You are removing my changes to the toolbar filter. 

`onFilter` function, `onFilter` and `hasInlineFilter` props from select (and maybe more, but I think these are the main removals)

2021-02-11 13:51 UTC, kialam requested changes

2021-02-11 13:58 UTC, jeanetteobr commented
@kialam @brumik  I am so terribly sorry about that! I will add that functionality back. Thanks for pointing it out!

2021-02-11 16:14 UTC, jeanetteobr commented
@kialam @brumik The missing props and onFilter method have been added back to this PR.

2021-02-11 16:29 UTC, brumik approved these changes
LGTM

2021-02-15 14:07 UTC, kialam approved these changes

2021-02-15 14:07 UTC, merged