Add all template details to popover.
RedHatInsights/tower-analytics-frontend pull request #415
Opened 2021-02-16 01:23 UTC by kialam

Spoke with @trahman73 on this and the easiest fix is to include all the sort by attributes/values returned by the API in the popover like so:

<img width="1405" alt="Screen Shot 2021-02-15 at 8 17 10 PM" src="https://user-images.githubusercontent.com/2293210/108007255-81b37c80-6fcb-11eb-90aa-eee28553bd09.png">

2021-02-23 16:15 UTC, benthomasson commented
https://issues.redhat.com/browse/AA-352

2021-02-23 16:35 UTC, brumik commented on src/Containers/AutomationCalculator/TopTemplates.js
> -                id,
Did you do this by accident? I am pretty sure I just destructured in a recent commit this object on your advice.

2021-02-24 08:01 UTC, brumik requested changes
Also if we merge the #416 first we could pass `sortAttr` directly instead of `sortBy`.

Except for the default value of the `sortBy` everything else is a nitpick (non-blockers).

2021-02-24 13:50 UTC, kialam commented on src/Containers/AutomationCalculator/TopTemplates.js
> -                id,
No, this is intentional. We are now passing in the entire api response to show in the tooltip so it makes less sense to destructure everything out in this case.

2021-02-24 14:26 UTC, brumik approved these changes
Thanks for including my nitpicks ^^ :heart:

2021-02-24 15:26 UTC, merged