Add toggle icon for sort order in filter toolbar.
RedHatInsights/tower-analytics-frontend pull request #416
Opened 2021-02-16 15:47 UTC by kialam

2021-02-23 16:16 UTC, benthomasson commented
https://issues.redhat.com/browse/AA-360

2021-02-23 16:38 UTC, brumik reviewed
I think this PR should wait for the backend PR to return the sort values without the :asc/:desc values?

2021-02-23 16:38 UTC, brumik commented on src/Components/Toolbar/Toolbar.js
> +                setFilter={value => setFilters('sort_attr', value.split(':')[0])}
We will need to remove the split

2021-02-23 16:43 UTC, kialam commented on src/Components/Toolbar/Toolbar.js
> +                setFilter={value => setFilters('sort_attr', value.split(':')[0])}
No, iirc sort_by will always be `attr:desc/:asc`.

2021-02-24 08:09 UTC, brumik commented on src/Components/Toolbar/Toolbar.js
> +                setFilter={value => setFilters('sort_attr', value.split(':')[0])}
Oh, wasn't @AparnaKarve PR was going to remove the `:asc/:desc` from the sort by options? (I cannot find the link to the backend pr, maybe somebody could link it here?)

2021-02-24 14:05 UTC, kialam commented on src/Components/Toolbar/Toolbar.js
> +                setFilter={value => setFilters('sort_attr', value.split(':')[0])}
Yes, but we still need to send it as `attr:asc/:desc` to the API and our queryParams do that (in PR #416)

2021-02-24 14:24 UTC, brumik commented on src/Components/Toolbar/Toolbar.js
> +                setFilter={value => setFilters('sort_attr', value.split(':')[0])}
This is PR #416 :confused: ? I am confused now

2021-02-25 00:03 UTC, AparnaKarve commented on src/Components/Toolbar/Toolbar.js
> +                setFilter={value => setFilters('sort_attr', value.split(':')[0])}
backend PR - https://github.com/RedHatInsights/tower-analytics-backend/pull/670

2021-02-26 17:03 UTC, kialam commented on src/Components/Toolbar/Toolbar.js
> +                setFilter={value => setFilters('sort_attr', value.split(':')[0])}
@AparnaKarve thanks

2021-03-09 17:54 UTC, jlmitch5 reviewed
This is looking great!  I think this squares with how I would expect the sorting functionality to work as a user.

I think there will need to be some updates to this based on the api.js work in https://github.com/RedHatInsights/tower-analytics-frontend/pull/424

Otherwise, I think this all makes sense and looks great!

2021-03-09 17:54 UTC, jlmitch5 commented on src/Api.js
> +        sort_by: `host_task_count:${params.sort_order}`
I guess we will move these changes to org stats based on the other pr doing that.

2021-03-09 17:54 UTC, jlmitch5 commented on src/Api.js
> +export const readJobsGroupByTemplate = ({ params = {}}) => {
I feel like these two functions should be updated to "readJobExplorer" and the params should be moved to clusters like you did with the org stats page in the other pr.

2021-03-09 17:54 UTC, jlmitch5 commented on src/Components/Toolbar/Toolbar.js
> +                onClick={() =>
woo!  this is definitely feeling how it should work I think!

2021-03-09 17:54 UTC, jlmitch5 commented on src/Containers/OrganizationStatistics/OrganizationStatistics.js
> +    return { ...rest, sort_by: [{ key: 'Order', value: 'Ascending/Descending' }]};
it sounds like we decided to remove this in the backlog grooming meeting.  should we just do that as part of this pr or as a follow up?  either is cool.

2021-03-09 17:54 UTC, jlmitch5 commented on src/Utilities/useQueryParams.js
> +            // I know this is ugly, we could put it into a middleware but I had
I would remove this comment, and add a comment as to why we are keeping this around in the two formats (which makes sense now that it's been explained to me, thanks @kialam. colon-separated for api use, split out into separate attrs for toolbar use)

2021-03-12 21:09 UTC, jlmitch5 commented
I have updated this PR and I believe it is ready for review, testing and merge.  Things I did:
- rebased to devel, updating new fetch calls to using the authenticatedFetch wrapper
- updated to getting new sort_options from api to display just the sortable attributes once (thanks @AparnaKarve for help understanding this).  In other words, this dropdown is no longer duplicated twice, appending each option with "ascending"/"descending".  **NOTE** that this requires api changes that are not yet pushed to cloud.redhat.com.  I had to run the api locally to get the options endpoint to update.
- updating all references of sort_attr to sort_options for consistency with the way this is phrased in the api
- fixed an issue where when sort_by is not set, updating the sort order or option could cause the page to error out.  I updated the useReducer actions to either look at "sort_by" if available, or the sort_options/sort_order keys on state.

2021-03-12 21:14 UTC, jlmitch5 commented on src/Utilities/constants.js
> +        sort_options: 'order',
I'm not sure what the correct option is here.  Somehow, I had code that had it "Order" capitalized, which didn't look right.  @AparnaKarve do you know what the default sort option is supposed to be for the org stats page?

2021-03-12 21:14 UTC, jlmitch5 commented on src/Utilities/useQueryParams.js
> +    const initialWithCalculatedParams = {
You would think this would make it so that sort_by is always there, but apparently not.

2021-03-12 21:51 UTC, AparnaKarve commented on src/Utilities/constants.js
> +        sort_options: 'order',
@jlmitch5 As far as I know, the dashboard pages (clusters and org stats) do not have sort options.

2021-03-13 09:46 UTC, brumik requested changes
It looks good and works, I have some questions regarding the code.

Otherwise, we should wait for the backend to be merged, we should track it in JIRA but we can link the backend PR here too

2021-03-13 09:46 UTC, brumik commented on src/Utilities/useQueryParams.js
> +    const initialWithCalculatedParams = {
Can you describe the workflow how you were able produce queryPramas values without sort_by? I was only able to do `sort_by: 'undefined:undefined'

2021-03-13 09:46 UTC, brumik commented on src/Utilities/useQueryParams.js
> +                if (state?.sort_by) {
* Can you clarify why is this logic needed here?
* I could not find it, what exactly the `?` does in the `state?`
* We could make it more compact by:
`const order = state.sort_by ? state.sort_by.split(':')[1] : state.sort_order`

2021-03-13 09:46 UTC, brumik commented on src/Utilities/useQueryParams.js
> +                if (state?.sort_by) {
The same as above

2021-03-13 09:46 UTC, brumik commented on src/Utilities/constants.js
> +        sort_options: 'order',
You don't have to, you can omit the whole line. The sort by is overwritten in the Api.js. As I told few days before we probably want to standardize and maybe a little rework the Api.js and the default query params (we may organize them by changeable and fixed for each call)

2021-03-15 16:57 UTC, brumik approved these changes
LGTM

2021-03-15 16:57 UTC, merged