Simplified Api.js and refactored Orgs page
RedHatInsights/tower-analytics-frontend pull request #424
Opened 2021-02-26 17:30 UTC by kialam

- Remove page-specific api methods in favor of generic ones
- Offload page-specific params to view component

2021-03-09 17:15 UTC, jlmitch5 reviewed
I think this is very nice.  It keeps the api file a bit simpler and mapped more 1:1 with endpoints, and it moves these params to the page where it makes sense to define them (better "separation of concerns").  I think this refactor will help us with maintaining this page and keep the api file from getting bloated.

All my suggestions are just low priority, small tweaks to potentially help tighten things up

2021-03-09 17:15 UTC, jlmitch5 commented on src/Api.js
>  const notificationsEndPoint = `/api/tower-analytics/v0/notifications/`;
while we are in here could we uncapitalize the "P"

2021-03-09 17:15 UTC, jlmitch5 commented on src/Api.js
>      const formattedUrl = getAbsoluteUrl();
might be cool to get rid of these forrmattedUrl vars and just put getAbsoluteUrl() direct in the new URL call

2021-03-09 17:15 UTC, jlmitch5 commented on src/Api.js
>      return fetch(url, {
I think we will need to update these to authenticatedFetch

2021-03-09 17:15 UTC, jlmitch5 commented on src/Api.js
> +export const preflightRequest = () => {
can we move preflightRequest above the v0 section, I think it's still in spec?

2021-03-09 17:15 UTC, jlmitch5 commented on src/Containers/OrganizationStatistics/OrganizationStatistics.js
> +        setOrgs(readJobsOrHosts({ params }));
totally fine with how it is here.  inlining it `setOrgs(chartMapper[activeTabKey].api({ params }));` might be slightly easier to parse, but either works

2021-03-14 15:28 UTC, brumik commented on src/Api.js
>  function getAbsoluteUrl() {
If we are here, can we convert these two functions to arrow functions, since we are using them everywhere.

The `getAbsoluteUrl` can be also simplified to onliner:
```js
const getAbsoluteUrl = () => window.location.href.split('/').slice(0, -1).join('/');
```

2021-03-14 15:38 UTC, brumik commented on src/Api.js
>  function getAbsoluteUrl() {
Or actually, we can just use `window.location.origin` which should give the same results more reliable.
![Screenshot from 2021-03-14 16-37-50](https://user-images.githubusercontent.com/8531681/111074532-a5db7e00-84e3-11eb-8c09-f878927ead55.png)

2021-03-15 16:23 UTC, kialam commented on src/Api.js
>  const notificationsEndPoint = `/api/tower-analytics/v0/notifications/`;
Good catch

2021-03-15 20:57 UTC, kialam commented on src/Api.js
>  function getAbsoluteUrl() {
Yes, `window.location.origin` is much cleaner.

2021-03-16 15:00 UTC, jlmitch5 requested changes
Again really loving that endpoints map 1:1 in the api file now, and queryParams are in the page files.  This is great!

2021-03-16 15:05 UTC, kialam commented on src/Containers/OrganizationStatistics/OrganizationStatistics.js
> +        sort_by: `host_task_count:${queryParams.sort_by}`
Ah yes, I lost my changes after the merge/rebase. Good catch!

2021-03-16 15:07 UTC, kialam commented on src/Containers/OrganizationStatistics/OrganizationStatistics.js
> +        sort_by: `host_task_count:${queryParams.sort_by}`
@jlmitch5 We also decided to hardcode those values. :)

2021-03-16 16:19 UTC, jlmitch5 approved these changes
nice!

2021-03-16 16:20 UTC, merged