Fix to render either error state or empty state component.
RedHatInsights/tower-analytics-frontend pull request #463
Opened 2021-05-03 19:00 UTC by h-kataria

Render error state or empty state component based upon `preflightError` or `error`, no need to render both components at the same time

Fixes https://issues.redhat.com/browse/AA-480

2021-05-04 07:32 UTC, brumik commented on src/Containers/Clusters/Clusters.js
>                  <Main>
If we are optimizing we can move the `<Main>` outside of the `if` statements:
```
<Main>
{if error && somecode}
{if not error && page }
</Main>
```
(Then also the React Fragment can be removed)

2021-05-05 13:50 UTC, h-kataria commented on src/Containers/Clusters/Clusters.js
>                  <Main>
@brum `<Main>` can be moved out for sure, but i still can not remove `<React.Fragment>` part because we do need that to wrap page header

2021-05-05 16:21 UTC, brumik commented on src/Containers/Clusters/Clusters.js
>                  <Main>
I meant the fragment on line 194 and the `Main` on line 195

2021-05-05 16:22 UTC, brumik approved these changes
Except for that one not important at all thing this is good to go

2021-05-06 19:25 UTC, h-kataria commented
@brumik please review unit tests. I tried to consolidate code using `<Main>` outside the code block but that did not work, so i am leaving that part as it is.

2021-05-10 08:39 UTC, brumik requested changes

2021-05-10 08:39 UTC, brumik commented on src/Containers/Clusters/Clusters.js
> +                <Router history={history}>
I am pretty sure this is going to the tests, not to the tested file. You should do something like this function with the react test renderer: https://github.com/RedHatInsights/tower-analytics-frontend/blob/devel/src/Utilities/tests/helpers.js#L18

(Also the bottom `</Router>` and `</>` are in swapped order)

2021-05-10 08:39 UTC, brumik commented on src/Containers/Clusters/Clusters.test.js
> +            global.fetch = jest.fn().mockImplementation(() =>
This is only working when there is only one call of fetch at the time on the page. When I was talking about dropping fetch-mock I thought something that we mock the `exports from the Api.js` with the help of function mocks:
https://jestjs.io/docs/es6-class-mocks. This would ensure we can return different data on different params passed to these functions and we would have full control of each type of call. However these mocks should be in a different file probably, and the data fo the mocks also somewhere in a folder called `fixtures` or similar.

2021-05-13 14:26 UTC, brumik approved these changes
@h-kataria It is good from my side, if you review it and you see it fit, merge it. (and sorry for messing up probably one of your commits when rebased, if you are keen on it I can go back and fix them)

2021-05-13 14:52 UTC, merged