Chrome 2 updade
RedHatInsights/tower-analytics-frontend pull request #464
Opened 2021-05-04 10:25 UTC by Hyperkid123

cc

2021-05-04 17:32 UTC, kialam requested changes

2021-05-04 17:32 UTC, kialam commented on config/dev.webpack.config.js
> +      useFileHash: false,
@Hyperkid123 How is cache busting implemented on the CRC side? We had to add hashes to our filenames and I'm curious as to why this has been removed as part of this PR.

2021-05-04 17:59 UTC, brumik commented
It's working for me, only getting warnings about
* "event imported as d3 was not found in d3"
*  `WARNING in shared module @patternfly/react-tokens
No required version specified and unable to automatically determine one. Unable to find required version for "@patternfly/react-tokens" in description file (/home/brum/Documents/AA/tower-analytics-frontend/package.json). It need to be in dependencies, devDependencies or peerDependencies.`

But the build, refresh, links, and clicks and tests are all fine

2021-05-04 18:02 UTC, brumik commented
Issue for chrome2 update in JIRA @Hyperkid123: https://issues.redhat.com/browse/AA-494

2021-05-05 03:58 UTC, Hyperkid123 commented on config/dev.webpack.config.js
> +      useFileHash: false,
Hashes are added to js assets in the config.

2021-05-05 07:56 UTC, Hyperkid123 commented
@brumik 
> WARNING in shared module @patternfly/react-tokens No required version specified and unable to automatically determine one. Unable to find required version for "@patternfly/react-tokens" in description file (/home/brum/Documents/AA/tower-analytics-frontend/package.json). It need to be in dependencies, devDependencies or peerDependencies.

Well that is because you are importing `react-tokens` in your code, but it's not listed as a direct dependency in your package.json. I will add it so the error goes away.

The d3 thing is caused by an invalid module definition. Nothing I can do about, we will just have to live with it.

2021-05-06 06:43 UTC, Hyperkid123 commented
@brumik looking the cypress issue right now. Also, the chunk loading errors are unfortunately a bug when using chromium-based browsers, source maps, and the browser debugger. We will most likely disable source maps inc the chroma adn see if it helps.

The d3 webpack erros are caused by different API in newer versions, you can check the chacngle log here: https://github.com/d3/d3/blob/master/CHANGES.md

2021-05-06 07:11 UTC, Hyperkid123 commented
@brumik @kialam can you trigger the cypress run? I was able to run it locally and most of the tests were passing. There were only some selector errors etc, which can be tuned later on. I just want to see if we can at least start the tests in CI env.

2021-05-06 12:33 UTC, Hyperkid123 commented
Oh I see there is a different proxy config for the cypress than in `local-frontend.js`. I need to update that as well.

2021-05-06 13:47 UTC, Hyperkid123 commented
@brumik @kialam I was able to run the cypress test even in CI, however, it's very non-deterministic. Sometimes a test passes, sometimes it does not. Mostly it's failing on proxy timeout or some runtime error tied to user identity. I will try to tinker around with it a bit more to make it more stable.

2021-05-11 07:23 UTC, rvsia commented
@Hyperkid123 the insights-proxy never worked for me on mac, so I am not the right candidate to test it. 😄

2021-05-11 12:11 UTC, brumik commented
@Hyperkid123 We disable cypress for the time being since we need a working environment, and we will need to fix it up later, as long as the only problem with the update will be cypress, this is good to go.

2021-05-11 22:52 UTC, kialam approved these changes
Everything seems to be working with the new proxy configs. I will note that developing with a local sidebar (e.g. serving `main.yaml` from cloud-services-config) doesn't work with new routes - they don't get redirected to `ansible/insights/new_route` @Hyperkid123 @ryelo . Is there a step I'm missing or a config file I need to look at to get a local side nav item to route correctly?

2021-05-12 07:05 UTC, Hyperkid123 commented
@kialam  correct me if I am wrong @ryelo, but if there are any redirects happening via Akamai (which I believe there are: https://github.com/RedHatInsights/cloud-services-config/blob/prod-beta/akamai/data/prod/base_rules.json#L1296) it won't apply to local development.

But you can add new entries to the proxy config to serve assets from desired routes. So you will basically have duplicate entries on different routes (as you have for stable/beta envs).
```jsx
// current
routes[`/ansible/insights`] = { host: `https://localhost:${FRONTEND_PORT}` };
// duplicates
routes[`/ansible/whatever`] = { host: `https://localhost:${FRONTEND_PORT}` };
routes[`/ansible/whatever/foo`] = { host: `https://localhost:${FRONTEND_PORT}` };
...
```

2021-05-12 09:55 UTC, brumik approved these changes
Works for me :+1:

2021-05-12 12:40 UTC, ryelo commented
Yes @Hyperkid123 that's correct

2021-05-12 14:19 UTC, merged