Broke up the tolbar filter item into smaller parts
RedHatInsights/tower-analytics-frontend pull request #473
Opened 2021-05-14 14:52 UTC by brumik

2021-05-25 17:33 UTC, jlmitch5 requested changes
This is looking good.  I'm wondering what you think about doing some renaming and moving some things around (see in-line comments).  I think this might help reduce some indirection, make it clearer which pieces are meant to be used where, and also just generally make things a little easier to understand.

2021-05-25 17:33 UTC, jlmitch5 commented on src/Components/Toolbar/Groups/FiltersCategoriesGroup.js
> +import ToolbarItem from '../ToolbarItems/';
I think renaming the folder to ToolbarInput (non-plural), as well as naming the index.js component ToolbarInput will help to make things a little clearer.

Specifically, ToolbarItem is a concept in core patternfly that I think we might be overloading here.  I think basically this "ToolbarInput" component switches the input type based on the options it is passed.

This is more preference and I'm fine either way, but it could be potentially be clearer if the ToolbarInput folder is nested inside Groups, where it is mean to be used.

2021-05-25 17:33 UTC, jlmitch5 commented on src/Components/Toolbar/Groups/FiltersCategoriesGroup.js
> +import CategoryDropdown from '../ToolbarItems/CategoryDropdown';
CategoryDropdown feels to me as if it is a part of the FilterCategoriesGroup component, rather than a toolbar item.  

The components are tightly and exclusively coupled, and both are < 50 LOC, so I'd recommend de-componetizing the CategoryDropdown (or moving the component definition) and inlining it in this file.  I think I'd prefer it not be exported (as it feels like something internal), but it's cool if it needs to to aid in making the existing tests work.

2021-05-25 17:33 UTC, jlmitch5 commented on src/Components/Toolbar/ToolbarItems/index.js
> +  select: CustomSelect,
Can we rename these to ToolbarSelectInput, ToolbarDateInput, ToolbarTextInput or some other consistent pattern.  I think it'd be helpful to call out they are specifically for use with ToolbarItem and not for sharing outside.

2021-05-26 13:07 UTC, brumik commented on src/Components/Toolbar/ToolbarItems/InputText.js
> +  const handleChips = () => {
We have cases for the other input types where in some places we need the chips, in others not (sort, quick date), and since we have the boolean in some fields, I think it is more consistent having it evrywhere. I hope I can move the chip logic later into a HOC component.

2021-05-26 13:09 UTC, brumik commented on src/Components/Toolbar/ToolbarItems/InputText.js
> +  const handleChips = () => {
Good one, I think I was planning it to handle more, but in this form, we can just inline it.

2021-05-26 13:11 UTC, brumik commented on src/Components/Toolbar/Groups/FiltersCategoriesGroup.js
> +import CategoryDropdown from '../ToolbarItems/CategoryDropdown';
Good one, I think I was planning it to handle more, but in this form, we can just inline it.

2021-05-26 13:11 UTC, brumik commented on src/Components/Toolbar/ToolbarItems/index.js
> +  select: CustomSelect,
Thanks, naming stuff is the hardest :+1:

2021-05-26 13:12 UTC, brumik commented on src/Components/Toolbar/Groups/FiltersCategoriesGroup.js
> +import ToolbarItem from '../ToolbarItems/';
Yes, I can rename it and if they are not used anywhere else than groups I will move there as a subfolder

2021-05-26 14:15 UTC, jlmitch5 commented on src/Components/Toolbar/Groups/FiltersCategoriesGroup.js
> +import CategoryDropdown from '../ToolbarItems/CategoryDropdown';
👍  ah yeah that makes sense.

2021-05-26 14:18 UTC, jlmitch5 commented on src/Components/Toolbar/ToolbarItems/InputText.js
> +  const handleChips = () => {
> We have cases for the other input types where in some places we need the chips, in others not (sort, quick date)

Totally, my thought here is I was wondering if we could introspect if chips show up rather than have it be something stored in configuration.  That being said, it's not a big deal having it in the config, and I agree with you, for this one, I think having it explicitly everywhere is a good thing.

2021-05-26 15:34 UTC, jlmitch5 approved these changes
Nice!

2021-05-26 15:34 UTC, merged