draft commit -- will rewrite commits to be nicer history later
RedHatInsights/tower-analytics-frontend pull request #474
Opened 2021-05-14 20:35 UTC by jlmitch5

This is an in progress PR of the Savings Planner add flow (not ready for merge just yet).

Currently, the pr:
- Adds “Add plan” button to Savings Planner card view to get to add screen
- Adds breadcrumb link back to savings planner list
- Adds in wizard component with hash-linkable steps (will be needed for edit view)
- Adds in grid-based form from PF
    - Some fields needed the ? Help popover link in the label of the field…I pulled in this component from awx.
- Adds in drag-orderable task adding list
    - Task add input allows both enter key-down and clicking “+” button to add
    - TODO: I added screen reader stuff based on the pf example, none of that is tested.  It may be potentially useful to check that stuff, but I’m not sure…maybe apurva knows (or knows someone who knows how to use that stuff).
    - Clicking the “x” in the remove will remove the task from the list.  I talked with Taufique and we decided against any sort of confirmation dialog for this particular interaction.
- Adds in radio single-select template list
    - Note, this is a simple, non-paginated DataList currently.  Will need to figure out with @akarve on the backend about pagination, searching, etc. in a follow-up PR

Here's what I'm looking to do before the PR is merged:
- TODO: Actual POST to API.
- TODO: Add proptypes to various files
- TODO: Fix random linting stuff

These TODOs I will probably do in a follow-up PR
- TODO: Add unit tests
- TODO: Disable save button when required fields aren’t entered, and have a tooltip of what needs to be added/where you need to go to do that.
- TODO: Add hiding of add button/redirection notice from view when user has read-only role (RBAC)

2021-05-20 17:08 UTC, kialam requested changes
Overall this is looking great, @jlmitch5 ! I think creating a reducer method to help set/get plan data to POST to the API would be beneficial here, so that's my one main request. 

Fantastic job!

2021-05-20 17:08 UTC, kialam commented on src/Containers/SavingsPlanner/Shared/Details.js
> +              onChange={(newName) => setName(newName)}
This would become `onChange={(newName) => { type: 'SET_PLAN_NAME', value: { newName } }}`

2021-05-20 17:08 UTC, kialam commented on src/Containers/SavingsPlanner/Shared/Form.js
> +          name,
Here you could just pass in `planData`.

2021-05-20 17:08 UTC, kialam commented on src/Containers/SavingsPlanner/Shared/Tasks.js
> +  const handleTextKeyDown = (e) => {
Nice

2021-05-20 17:08 UTC, kialam commented on src/Containers/SavingsPlanner/Shared/Tasks.js
> +  const removeTask = (task) => {
Love the remove method - a very thorough and well-thought out UI for the tasks list!

2021-05-20 17:08 UTC, kialam commented on src/Containers/SavingsPlanner/Shared/Templates.js
> +import React from 'react';
We are going to replace this in a follow up PR with a paginated data list of templates so works for now 👍

2021-05-20 18:08 UTC, jlmitch5 commented on src/Components/Toolbar/Toolbar.js
> +          {additionalControls.length > 0 && (
yes.  additionalControls is a pattern I pulled from tower.  It is how things like Add, Delete, etc. buttons are added to the toolbar.  Since it has always seem to work well for providing a spot to put arbitrary buttons and things towards the end, I decided to introduce the pattern here.

My preference would be to do what is done there to be consistent, and if we run into things specific to this app, we can approach that way.  What do you think?

2021-05-20 18:09 UTC, jlmitch5 commented on src/Containers/SavingsPlanner/SavingsPlanner.js
> +            ...(canAddPlan
I can pull this up above as a constant.  I inlined it because that is how it is done in tower.

I would probably make it a function, just an array constant.

2021-05-20 18:11 UTC, jlmitch5 commented on src/Components/Popover.js
> +  if (!content) {
This is another one I pulled straight from Tower...I honestly didn't look very closely, just that pulling in the component worked for what I wanted out of the box.

I can see if there's a way to clean up.

2021-05-20 18:14 UTC, jlmitch5 commented
Thanks for the great review!

I'm not as familiar with the custom hook/reducer pattern, but now that you've explained it and I've done a bit of research, I totally agree with you, it seems like it would be a great fit for this!  It felt weird passing in so many props to the wizard steps, but I knew I wanted all of the plan data to roll up to the root form component.  This seems like a way that would allow me to do that but keep the API of those step components much tighter.  Thanks for the suggestion!

Popover and Toolbar additionalControls I'll discuss with you offline to see how/if we should tackle those differently.

2021-05-21 07:37 UTC, brumik requested changes
Kia did the hard work in the previous PR review and I could only agree with her (this is a really good job here). 

I just made some advice on the reducer best practices (last commit). These things will make the code more future proof and bring it closer to the TS if we want to migrate in the future maybe.

I would definitely like to see the reducer exporting only a `dispatch`, `formData` and lots of actions constants here, so it could be used like:

`dispatch({ type: ACTION_CONST_IPORTED_FROM_THE_HOOK_FILE, value })`

2021-05-21 07:37 UTC, brumik commented on src/Utilities/useForm.js
> +        throw new Error();
If this gets here it breaks the application, can we add at least a string saying "useFormReducer `action.type` was not found"?

2021-05-21 07:37 UTC, brumik commented on src/Utilities/useForm.js
> +      case 'SET_FIELD':
I definitely do not prefer this style. If we use a reducer we should create an action for each possible action we can do, even if it is the same handler. As I see it before for example "SET_TEMPLATE_ID", "SET_SOME_OTHER", "DELETE_TEMPLATE_ID", "RESET_FORM" etc...

These string constants could live as exportend constants, so we can just export the `formData`, `dispatch` and then we can pull the action name constants fomr other firles. This makes this reducer TypeScript ready.

2021-05-21 07:37 UTC, brumik commented on src/Utilities/useForm.js
> +    ...initial,
If there is a set of values, we should initialize all of the attributes here, even if they are not passed in the `initial` value.

2021-05-21 07:37 UTC, brumik commented on src/Utilities/useForm.js
> +  };
we definitely want to export dispatch too

2021-05-21 07:37 UTC, brumik commented on src/Containers/SavingsPlanner/Shared/Form.js
> +      delete formData.template_id;
When using reducers, this is not the best way (I am surprised it works) to do this. If you don't want to modify the data permanently then create a copy of the form data (`{ ...formData }`), if the `formData` should change permanently then create a dispatch action for removing the template id and updating the tasks. Objects in react should be immutable.

2021-05-21 16:10 UTC, kialam commented on src/Containers/SavingsPlanner/Shared/Form.js
> +    formData.tasks = formData.tasks.map((task, index) => ({
Can the hook create the tasks array instead of having the logic here?

2021-05-21 17:52 UTC, brumik approved these changes
My suggested changes are non blocking and can be done in a later in a followup PR

2021-05-24 15:09 UTC, kialam commented
These changes can be made in a separate PR.

2021-05-24 15:09 UTC, kialam approved these changes

2021-05-24 17:02 UTC, jlmitch5 commented
Merging now, will follow up from feedback in the next pr!

2021-05-24 17:03 UTC, merged