Visual updates to the statistic page
RedHatInsights/tower-analytics-frontend pull request #492
Opened 2021-06-07 14:15 UTC by brumik

2021-06-09 19:37 UTC, jlmitch5 requested changes
This is looking great!  A few things:
- change the big hours number to blue (inline comment)
- looks like the top of the elapsed line is getting cut off, with these values:
![Screen Shot 2021-06-09 at 3 32 34 PM](https://user-images.githubusercontent.com/1342624/121417576-10138b80-c938-11eb-8f07-ce21c2047d1a.png)

![Screen Shot 2021-06-09 at 3 31 10 PM](https://user-images.githubusercontent.com/1342624/121417645-21f52e80-c938-11eb-9f66-8ac2742ba169.png)

It's also a bit strange that the largest y tick is bigger than the others.  I feel like one tick worth of padding above the line would be ideal visually

- we should set radix (I think that's what it's called) to always 2 decimal points and have the $ prepending the values
![Screen Shot 2021-06-09 at 3 29 30 PM](https://user-images.githubusercontent.com/1342624/121417788-451fde00-c938-11eb-9db2-007b4178b1f9.png)

- We should have the same labels for these tooltips as the money (cost/benefits)...it is still cost and benefits, but just in terms of hours instead of money.  These labels were also chosen to be consistent with the legend on the right so it is easy for the user to connect the two together without thinking about it.  Append hours after the number.

![Screen Shot 2021-06-09 at 3 29 30 PM](https://user-images.githubusercontent.com/1342624/121418092-9a5bef80-c938-11eb-83c0-211c45263036.png)

2021-06-09 19:37 UTC, jlmitch5 commented on src/Containers/SavingsPlanner/TotalSavings.tsx
> +        style={{ color: 'var(--pf-global--success-color--200)' }}
this changes based on isMoney see mockups

2021-06-09 19:37 UTC, jlmitch5 commented on src/Containers/SavingsPlanner/StatisticsTab.tsx
> +  const getXOffsetForAxis = (ticks: number[], height = 600): number => {
i see from your comment these will be moved out to the chart renderer (which I think will be good and help reduce the complexity in this file).

2021-06-09 19:37 UTC, jlmitch5 commented on src/Containers/SavingsPlanner/StatisticsTab.tsx
> +const formatNumberAsK = (n: string | number): string => {
typo (upper-case K)

2021-06-09 19:37 UTC, jlmitch5 commented on src/Containers/SavingsPlanner/StatisticsTab.tsx
> +   * @param ticks The ticsk for the chart where the edge ticks are the domain for the chart.
typo ticsk

2021-06-10 09:37 UTC, brumik commented
@jlmitch5 thanks for your review, to go in order:
I can correct the typos and the hour's number color, however, the tooltips are a bigger chunk of work, and I am actively working on it in the chart builder. Currently what you want is not possible.

Also, the Y-axis size === maximum (it's not cut off, it is exactly as big as the axis :D) value is already addressed in my lib and I am preparing another PR for upgrading the version of the charting library.

2021-06-10 09:59 UTC, brumik commented on src/Containers/SavingsPlanner/TotalSavings.tsx
> +        style={{ color: 'var(--pf-global--success-color--200)' }}
Done :+1:

2021-06-10 13:20 UTC, jlmitch5 approved these changes

2021-06-10 13:24 UTC, merged