Update Modal to meet Patternfly specifications
RedHatInsights/tower-analytics-frontend pull request #497
Opened 2021-06-14 19:30 UTC by knightsean00

![image](https://user-images.githubusercontent.com/13596473/121948454-1f198580-cd0c-11eb-81cf-5259a0743e03.png)

Now includes a job breakdown bar, DescriptionList stats, and TableComposable related jobs.

2021-06-22 14:47 UTC, brumik commented on src/Components/Breakdown.js
> +  const totalCount = Object.keys(categoryCount).reduce(
Just for your information, you can use the [`Object.values()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values) here and similar situations.
(And probably could have names the `a` and `b` variables a little better :P but I am nitpicking here)

2021-06-22 14:53 UTC, brumik commented on src/Components/ModalContents.js
> +      setRelatedJobs(readJobExplorer({ params: relatedTemplateJobsParams }))
Eslint fix :) (on the whole file, there are also unused variables - mainly stylings). You could probably use an editor with linting highlights to make your work better ^^

2021-06-22 15:03 UTC, brumik requested changes
As the previous PR reviews, please use some kind of lint fixer, I know that our CI lint checking is kinda broken. You have plenty of unused variables from imports and custom-styled components, please remove them before merging.

2021-06-22 15:03 UTC, brumik commented on src/Components/ModalContents.js
> +    success: "#95D58E",
These colors don't match the chart color (bar and line), we need to update one or another to match. I think this can be outside of this PR but we should mark it up in JIRA then. @jlmitch5

2021-06-22 15:06 UTC, brumik commented on src/Components/ModalContents.js
> +    success: "#95D58E",
And just out of curiosity, where did you get these exact colors in this list?

2021-06-22 18:47 UTC, knightsean00 commented on src/Components/ModalContents.js
> +  if (stats == null || stats == 0) {
The tests have been updated in the most recent commits.

2021-06-22 18:48 UTC, knightsean00 commented on src/Components/ModalContents.js
> +    success: "#95D58E",
I was given these colors:
![image](https://user-images.githubusercontent.com/13596473/122982459-bfe0f400-d34f-11eb-9f60-a281b8fb2ada.png)

I kind of just guessed the rest, but I assumed that someone else would probably know much more than I would about the correct color usage. I was going to bring that up as an issue whenever this pull request was approved.

2021-06-23 06:45 UTC, brumik commented on src/Components/ModalContents.js
> +    success: "#95D58E",
Oh, okay, then I think we can pull these variables from `patternfly-tokens`. And if this is the pf coloring then we probably should update the other charts to match up.

2021-06-23 07:13 UTC, brumik requested changes
It is great and nearly there. I didn't understand why is the function commented out, and that is the blocker. 

I like how this refactor made the code more DRY.

However, I spotted a problem while reviewing: the modal window has an API call and does not handle the loading, and the error states. This causes the modal window to show for a second the previous modal window data on open. If you want, tackle this in this PR or in a follow-up PR, if not, I'll make a ticket and will do it later :)

2021-06-23 07:13 UTC, brumik commented on src/Components/ModalContents.js
> +// const formatTopFailedStep = (data) => {
Why is this function just commented out?

2021-06-23 07:13 UTC, brumik commented on src/Components/ModalContents.js
> +// const formatTopFailedStep = (data) => {
Why is this function just commented out?

2021-06-23 07:13 UTC, brumik commented on src/Components/ModalContents.js
> +    success: '#95D58E',
As I mentioned before we could use the PF tokens to get these values from https://www.npmjs.com/package/@patternfly/react-tokens. I am fine if this is in a followup PR.

2021-06-23 19:22 UTC, knightsean00 commented on src/Components/ModalContents.js
> +// const formatTopFailedStep = (data) => {
I left the function commented out because it seemed like it might be needed later if more information needs to be included in the modal. If we end up not using it I'll just delete it

2021-06-23 19:55 UTC, knightsean00 commented on src/Components/ModalContents.js
> +    success: '#95D58E',
Resolved in most recent commit

2021-06-23 20:25 UTC, brumik commented
@knightsean00 can you please rebase to devel? The lint check should be fixed there now :)

2021-06-24 11:25 UTC, brumik approved these changes
LGTM
Followup - Modal API status handling, removing the commented code
Potential follow-up work: Upgrade and get the chart builder to create horizontal bar charts.

2021-06-24 11:37 UTC, merged