Update JobExplorer to use Composable Table
RedHatInsights/tower-analytics-frontend pull request #498
Opened 2021-06-14 20:49 UTC by knightsean00

![image](https://user-images.githubusercontent.com/13596473/121957486-4f1a5600-cd17-11eb-8b08-a4528d20426c.png)

2021-06-17 19:22 UTC, jlmitch5 requested changes
This looks and functions fantastic...and you've been able to delete over a 100 LOC in favor of using patternfly standards!

I think conceptually it would be a bit simpler if id from the api was used instead of array or row indexes.

2021-06-17 19:22 UTC, jlmitch5 commented on src/Components/JobExplorerList.js
> +            rowIdx += 2;
use the job's id for key purposes as well, I don't believe index of the map or the row is needed for uniquity, as the id will always be present and should always be unique.

2021-06-22 14:41 UTC, brumik reviewed
Please run lint fix on this file (i am using vscode where you can do it from its commands, so I cannot supply you with an npm command which fixes one file, however, you can run `npm run lint:js:fix` to run on all files, commit this only file and discard changes on the other ones as workaround).

Also, the list seems to work fine :+1:

2021-06-22 14:41 UTC, brumik commented on src/Components/JobExplorerList.js
> +                <Tr isExpanded={expanded[idx] === true}>
I don't know about this, but in the [examples](https://www.patternfly.org/v4/components/table) they seem to use the `ExpandableRowContent` component for this kind of functionality. But I never worked with the table component so @jlmitch5  probably has more insight into this.

2021-06-22 17:12 UTC, knightsean00 commented on src/Components/JobExplorerList.js
> +                <Tr isExpanded={expanded[idx] === true}>
Alright, my latest commit should have linting all set up, I forgot to create a .vscode config for my local directory.

I actually based my usage of the Expandable TableComposable from the PatternFly examples, so, as for the usage of `ExpandableRowContent`, it looks like they use it as a child of <Td> under <Tr>

![image](https://user-images.githubusercontent.com/13596473/122970104-54445a00-d342-11eb-9f4e-ee29e7ac3fd1.png)

2021-06-23 06:43 UTC, brumik approved these changes
I love how this refactor turned out, so satisfying :clap:

2021-06-24 14:11 UTC, jlmitch5 requested changes

2021-06-24 14:11 UTC, jlmitch5 commented on src/Components/JobExplorerList.js
> +        {jobs.map((job, idx) => (
rather than using idx here, i would just use the job's id as the key to do everything off of.

2021-06-24 15:11 UTC, brumik commented on src/Components/JobExplorerList.js
> +            <Tr isExpanded={expanded[job.id.id] === true}>
you cna use instead of `expanded[job.id.id] === true` just `!!expanded[job.id.id]`

2021-06-24 15:23 UTC, brumik commented on src/Components/JobExplorerList.js
>    windowWidth: PropTypes.number,
If jobs has no default value in the destructuring it should be required. And I think `windowWidth` is not used anymore.

2021-06-24 15:27 UTC, brumik commented on src/Components/JobExplorerList.js
> +        {jobs.map((job, idx) => (
In situations like this I like to create a small dump component for each entry that manages its own `[expanded, setExpanded] =  useState(false)` state. I think that is the most readable way to go about it. What do you think @jlmitch5 ?

2021-06-29 11:57 UTC, brumik commented on src/Components/JobExplorerList.js
> +const Row = ({ job }) => {
I think we are having separate files for each component. This could be in its own too (as John mentioned yesterday something like: `JobExplorerListRow`)

2021-06-29 17:21 UTC, knightsean00 commented on src/Components/JobExplorerList.js
> +const Row = ({ job }) => {
Oh, my bad, I thought that since it was a dump component I was just gonna put it in the same file like we have with other components.

2021-06-30 04:22 UTC, jlmitch5 commented
Layout for the expanded row seems slightly awkward...I'd like to see three rows of the same width (and shrinking to two/one column for responsiveness

<img width="1272" alt="Screen Shot 2021-06-30 at 12 18 57 AM" src="https://user-images.githubusercontent.com/1342624/123901500-0c709480-d939-11eb-877e-d60317a97d8c.png">

I don't think we need to use TDs for the expanded content...rathere, I think we can just treat this expandable section as a pane and do arbitrary layout.  In this case, I think the DescriptionList pf components like we did for the savings planner detail screen would work well for this.

2021-07-01 13:53 UTC, jlmitch5 approved these changes
Awesome looks great!

2021-07-01 17:20 UTC, merged