[WIP] Feature flags
RedHatInsights/tower-analytics-frontend pull request #517
Opened 2021-07-02 08:49 UTC by brumik

Starting to add feature flags handler. Waiting for @jameswnl to get the flags from the server
The problem may be that I am unable to test it on the cloud, and local backed may not cointains the featureflags endpoint.

The context provider and the consumer works like charm otherwise :)

2021-07-06 14:24 UTC, jlmitch5 requested changes
looks good just a couple things

2021-07-06 14:24 UTC, jlmitch5 commented on src/Api.js
> +const readWithPagination = (endpoint, params) => {
very nice abstraction!

2021-07-06 14:24 UTC, jlmitch5 commented on src/Api.js
>  export const readClustersOptions = ({ params = {} }) => {
The options here all look identical too.  could you make a similar function for these?

2021-07-06 14:24 UTC, jlmitch5 commented on src/FeatureFlags/FeatureFlag.tsx
> +export default FeatureFlag;
export so that this is used

```
useFeatureFlags()
```

2021-07-06 14:34 UTC, brumik commented on src/Api.js
>  export const readClustersOptions = ({ params = {} }) => {
I was thinking about it but it is a little, maybe we can export the `endpoints` and have one function for reading the options and one for reading the data? :) that way a new endpoint would be just about defining and exporting the route

2021-07-07 14:38 UTC, jameswnl commented on src/Api.js
> +const featuresEndpoint = '/api/featureflags/';
Currently, it is being served at `/api/featureflags/v0`

2021-07-08 14:54 UTC, jlmitch5 approved these changes

2021-07-09 09:51 UTC, merged