Add two new unit tests
RedHatInsights/tower-analytics-frontend pull request #523
Opened 2021-07-08 17:23 UTC by knightsean00

2021-07-16 08:20 UTC, brumik requested changes
I like the overall work :+1:  I have some suggestions how could the tests be further improved :)

2021-07-16 08:20 UTC, brumik commented on src/Containers/SavingsPlanner/Add/index.test.js
> +    var wrapper;
Using `var` was the main source of confusion and bugs before the `let` era. The difference is explained [here](https://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var) pretty well. It is nothing wrong to use it, but it is not considered a good practice anymore.

2021-07-16 08:20 UTC, brumik commented on src/Utilities/tests/helpers.reactTestingLib.js
> +export const renderPageWithProps = (
When I wrote the `renderPage` I didn't considered props and other components that will need provider and router.

Can you (in this or a followup PR) unify these two functions like:
```js
export const renderComponentWithUtils = (Compoenent, { search } = defaultParams, props = {} ) => render(...);
```
If you have better name for it I'll take it, I could not come up with better rn :D

2021-07-16 08:20 UTC, brumik commented on src/Containers/SavingsPlanner/Shared/Form/Steps/Templates/index.test.js
> +    fireEvent.click(screen.getByTestId('radio-1'));
:+1: I like that you added a testId

Maybe you should test if the click did something or not (I would move that to another test case `it open the row when clicked on it`)

2021-07-16 08:20 UTC, brumik commented on src/Containers/SavingsPlanner/Shared/Form/Steps/Templates/index.test.js
> +    api.readJobExplorer.mockResolvedValue({
I think the mock for this job explorer could go into the `__fixtures__` too with some descriptive name. When we created fixtures we planned to have responses there for most of our queries so we can reuse them in different suites if needed.

(This is also true for the `planOptions` tests with the `rbac false`)

2021-07-16 17:50 UTC, knightsean00 commented on src/Containers/SavingsPlanner/Add/index.test.js
> +import '@testing-library/jest-dom';
I'm using a function (`toBeEmptyDOMElement()`). Also this package is just an extension of `testing-library` as a whole with quite a bit more functionality, so I thought it would be a useful addition as we begin to migrate from Enzyme.

2021-07-16 18:05 UTC, knightsean00 commented on src/Containers/SavingsPlanner/Add/index.test.js
> +    expect(wrapper.container).toBeEmptyDOMElement();
I couldn't find a good way to determine if the page was empty based on just `screen` alone

2021-07-16 18:07 UTC, knightsean00 commented on src/Utilities/tests/helpers.reactTestingLib.js
> +export const renderPageWithProps = (
Wait sorry, isn't that already done?

2021-07-16 18:21 UTC, jlmitch5 commented on src/Containers/SavingsPlanner/Add/index.test.js
> +    expect(wrapper.container).toBeEmptyDOMElement();
I like this approach.  It's mentioned in the testing-library docs https://testing-library.com/docs/ecosystem-jest-dom/

I think this well help make things a bit easier to implement, as @knightsean00 mentions

2021-07-16 18:25 UTC, jlmitch5 reviewed
Really great tests.  I've piggy-backed my review off of @brumik's which had some good thoughts.

2021-07-16 18:25 UTC, jlmitch5 commented on src/Containers/SavingsPlanner/Add/index.test.js
> +import '@testing-library/jest-dom';
see other comment in this file

2021-07-16 18:25 UTC, jlmitch5 commented on src/Containers/SavingsPlanner/Shared/Form/Steps/Templates/index.test.js
> +    api.readJobExplorer.mockResolvedValue({
I agree with @brumik moving this out to fixtures makes a lot of sense

2021-07-16 18:25 UTC, jlmitch5 commented on src/Containers/SavingsPlanner/Shared/Form/Steps/Templates/index.test.js
> +    fireEvent.click(screen.getByTestId('radio-1'));
I'm fine either way here.

2021-07-17 07:49 UTC, brumik approved these changes
Looking great 👏

2021-07-17 07:49 UTC, brumik commented on src/Containers/SavingsPlanner/Add/index.test.js
> +    expect(wrapper.container).toBeEmptyDOMElement();
I still don't like using the `.container` but it does its job.

2021-07-17 09:10 UTC, merged