Replaced use of useApi hook with useRequest
RedHatInsights/tower-analytics-frontend pull request #527
Opened 2021-07-12 14:45 UTC by h-kataria

- Also intorduced qs hook, so users can now be able to save the url and load the page using the params in url, page reloads if user makes a change to url or change params from search/filters toolbars

2021-07-14 09:05 UTC, brumik requested changes
There are lots of linting problems which I believe can be fixed automatically (I am not sure if it fixes unused imports and variables).

I was able to go trough the first 10 files out of 27 as this PR is huuuuge :clap: :+1: (I bow to your endurance @h-kataria):
* On the automation page as I commented bellow the useRequest is now used to fetch the API even when we want to recalculate the data locally (I believe the useRequest has something for this use case too :)
* Automation calculator page has no chips, but the url shows the query params, which would be a little odd for me as an user
* The URL exposes the `attributes` param from the queryParams which should be hardcoded for most of our cases and this way the user can modify it, causing some pages or later reports to break (eg removing an attr which is displayed in a chart) 
* Modifying anything in the URL to incorrect value causes the API to fail (@jlmitch5 because of this exposition as a raw serialized string I am not sure the URL as the source of truth is the right approach, they can modify an object which is used for API calls directly from the URL to ANY value, they can add fields, or change any values).

As my feelings about this: I can understand the reason why we want to move towards useRequest since it is used in other places, but I feel it is just a little too complicated and more code as well.

As I mentioned above I have concerns about the URL as the single source of truth. However the code for synching could be improved too. I think we could isolate more the code pieces responsible for the queryParams -- url sync, since now it weaves trough all of the application (even touching the toolbar which should be a standalone, reusable component).

On that note: if the query params is in the URL bar it means it is global for the page so we could utilize a react context or redux (already in app too) to make the queryParams a true global state, and then just automagically sync in the background with the URL (one way or another)

2021-07-14 13:58 UTC, jlmitch5 requested changes
Thanks for taking this on!  Looks great generally!

My one higher level question is about queryParams.  I believe this is using the useQueryParams hook, and tower uses the qs service.  I'm curious how the approaches differ and if that will lead to any ux discrepancies across the platform.

Otherwise, just a small thing I've seen so far

2021-07-14 13:58 UTC, jlmitch5 commented on src/Utilities/helpers.js
> +export const qsToObject = (qs) => {
I would prefer these be in a qs utility rather than this catch all utilities file (which honestly, I'd eventually prefer to split apart move all this stuff to either more explicit helper files, or to shared utilities within a screen if they are only used in one place.

2021-07-19 20:50 UTC, jlmitch5 commented
@h-kataria @brumik I've filed a follow-up issue for the refactor work we discussed in the sync-up today

2021-07-19 21:06 UTC, jlmitch5 requested changes
I looked over the more infrastructure-related code pretty thoroughly and then skimmed through all the implementations in the screens files.  I think this is great!  Just a few small clean up things and I think this is ready for merge.

2021-07-19 21:06 UTC, jlmitch5 commented on src/Components/Toolbar/Toolbar.js
> +    params = replaceParams(params, { [key]: value });
again, I think you can get rid of this replaceParams line (see comment in helpers)

2021-07-19 21:09 UTC, h-kataria commented on src/Utilities/helpers.js
> +  params = replaceParams(params, { [key]: value });
this line i believe is used, when selecting quick_date_range value, that is a single select.

2021-07-20 16:57 UTC, jlmitch5 approved these changes
Looks good!

2021-07-21 14:45 UTC, brumik approved these changes

2021-07-21 14:49 UTC, brumik requested changes
Working on the ROI update bug

2021-07-21 16:07 UTC, brumik approved these changes
Everything is working

2021-07-21 16:07 UTC, merged