[AA-177] Add column sorting to JobExplorer table
RedHatInsights/tower-analytics-frontend pull request #535
Opened 2021-07-22 21:46 UTC by knightsean00

https://issues.redhat.com/browse/AA-177

2021-07-26 11:09 UTC, brumik requested changes
Would you consider moving the sort attribute names into a map like in the [Reports page](https://github.com/RedHatInsights/tower-analytics-frontend/pull/524/files#diff-41188b63e584a595b8a63e3a2a38a578a151cb62206f6468305d353a6474d22eR192) (it is not merged yet).

I wrote a small logic around it operating on the API format (array of `{ key: 'name', value: 'Id/Name'}`) so we can use it with the API options results too :) I think it  would be beneficial if we could later on extract this logic and just apply to all current and future tables :)

2021-07-26 11:09 UTC, brumik commented on src/Components/JobExplorerList.js
> +  'Id/Name': 'id',
Using a capitalized key in objects is not too good practice. If it is easy to change up the key - value pair or de-capitalize them in this object I think we should do it (if it is not easy we can leave it like this)

2021-07-26 16:28 UTC, jlmitch5 commented on src/Components/JobExplorerList.js
> +  'Id/Name': 'id',
It does seem like I'd expect this to be inverted, as key: value, usually == key: label

2021-07-27 07:41 UTC, brumik requested changes
The code looks good, but when pressing sorting, the table is not changed to loading component, but the loading is rendered above the table, causing the page to flicker on fast network and on slow networks it is confusing to see the loading component and the table too.

2021-07-27 07:47 UTC, brumik approved these changes

2021-07-27 17:46 UTC, merged