[AA-178] Add Breakdown bars to JobExplorer Table
RedHatInsights/tower-analytics-frontend pull request #536
Opened 2021-07-22 23:44 UTC by knightsean00

https://issues.redhat.com/browse/AA-178

For some reason, I have not seen an example of what `most_failed_task` would look like in the production data so I have yet to make Breakdown bars for those yet. If someone (@brumik , @h-kataria , @jlmitch5 ) has any idea, please let me know so that I can complete this section.

![image](https://user-images.githubusercontent.com/13596473/126722258-cb9512a3-a440-476f-819a-64808ed20681.png)

2021-07-26 10:30 UTC, brumik commented on src/Components/Breakdown.js
> +  showPercent: PropTypes.bool,
If it is not required then please provide a default (`false`) default value to it. It will evaluate the same (as undefined and null is false in a condition too) but by providing a default value we know that it is a false boolean. It is a nice practice and also helps when converting to TS :)

2021-07-26 10:33 UTC, brumik commented on src/Components/JobExplorerListRow.js
> +} from '@patternfly/react-tokens';
This is great :+1: was it provided to you or you found out yourself? We should consider to extract these colors somewhere since we are using them in the icons too: ([`JobStatus.js:15`](https://github.com/RedHatInsights/tower-analytics-frontend/blob/devel/src/Components/JobStatus.js#L15))

2021-07-26 10:47 UTC, brumik requested changes
It is looking good :) 

We are doing so much checking for the `job` having certain values. We could just provide a default value to it and forget about checking maybe?

2021-07-26 10:47 UTC, brumik commented on src/Components/JobExplorerListRow.js
> +  if (failed_tasks != null) {
Can we break up this multiple conditional return statements to more readable sub functions (or components if it looks like it could be extracted into its own component - basically if you can name it reasonably it can be probably a component).

2021-07-26 10:47 UTC, brumik commented on src/Components/JobExplorerListRow.js
> +          <React.Fragment />
Please use the `<>` shorthand for `<React.Fragment>`. If you want to return nothing from the component please use `null` or `''` (empty string) - TS prefers empty string :). Since the react fragment does create a DOM element (empty div pair) while the `''` or 'null` return do not create any DOM elements.

2021-07-26 10:47 UTC, brumik commented on src/Components/JobExplorerListRow.js
> +        ok: job?.ok_host_count ? job.ok_host_count : 0,
You can use the shorthand `??`. Basically:
```js
let job = { ok: 10 };
job?.ok ?? 0 // 10
job?.xx ?? 0 // 0
// BEWARE: 
job?.ok || 0 // 0
```

Basically `??` checks if it is returned null or undefined, while `||` converts it to boolean and check is then for true/false.

I think when the `job` is not defined we could return the object with all the fields set to `0` as in the check for the individual fields.

2021-07-26 10:47 UTC, brumik commented on src/Components/JobExplorerListRow.js
> +  const categoryColor = {
We already have a color map defined at the start of the file. Can we merge the two?

2021-07-26 10:47 UTC, brumik commented on src/Components/JobExplorerListRow.js
> +      value: job.host_task_count ? job.host_task_count : 0,
Same as before with the `??`

2021-07-26 16:24 UTC, jlmitch5 commented on src/Components/JobExplorerListRow.js
> +          <React.Fragment />
I wonder if there's a "prefer <> format for fragments" linting rule we could add?

2021-07-26 19:30 UTC, knightsean00 commented on src/Components/JobExplorerListRow.js
> +} from '@patternfly/react-tokens';
Not gonna lie I just kind of guessed those colors lol. It would be nice if Taufique could give some input on these color choices.

2021-07-27 07:34 UTC, brumik approved these changes
This is looking good already. Please update the default params and it is good to go ^^.

2021-07-27 07:34 UTC, brumik commented on src/Components/Breakdown.js
> +  showPercent: false,
Once Ben sent me a link why `defaultProps` is not preferred over defining the default value while de-structuring the params. I cannot find the link anymore, but it broke down to performance issues. While default props is running trough the react framework, the de structured default value is created at compile time. So since then I am using the destructuring for defining default value. 

Can we move it there (params destructuring) too?

2021-07-27 07:34 UTC, brumik commented on src/Components/JobExplorerListRow.js
> +} from '@patternfly/react-tokens';
Yeah :D maybe we can ask Taufique him to provide some guidelines or colors in the mockup or alongside of it

2021-07-27 07:34 UTC, brumik commented on src/Components/JobExplorerListRow.js
> +      <br></br>
Is this by accident or you want to render two empty lines? (<br> is a simple html tag without closing pair so </br> also renders a empty line). If you want space maybe you can use css margin to make it happen instead? Then we could remove the br and the react fragments.

2021-07-27 18:20 UTC, merged