- split useRequest requests into individual requests
RedHatInsights/tower-analytics-frontend pull request #538
Opened 2021-07-23 02:12 UTC by h-kataria

- And fixed to load correct contents in modal when template/wokflow is selected

@knightsean00 this addresses the bug you found. @jlmitch5 please review.

2021-07-23 06:37 UTC, brumik requested changes
Please fix linting, and tests.

Also it does not seem to work, anytime I open a template modal I get the `No template name` and empty modal body.

2021-07-23 06:37 UTC, brumik commented on src/Components/ModalContents.js
> +    { relatedJobs: {} }
Can we return just the items we need and not wrap everything in another object. I know that you used this pattern everywhere but it is just adding an unnecessary wrapper object what we de-structure nearly everywhere instantly.

2021-07-23 06:37 UTC, brumik commented on src/Components/ModalContents.js
> +    { stats: {}, statsError, statsIsLoading, statsIsSuccess }
This default value I believe is for the `result` variable. You are also using `variables` for defining it which is not bad, but yo uare using variables which are returned to you from this function so they are "used before defined". In JS you can do this, but the value of the variable will be `undefined` and it is considered a bad practice as it can cause confusion.

2021-07-23 06:37 UTC, brumik commented on src/Components/ModalContents.js
> +      return { stats: stats.items[0] };
I am not sure, but you may want the aggregate values:

Which you can get more accurately from the `apiData.meta.legend` as it is now returned in every call. Please consider looking into what is needed and if you can get it from the meta. The `items` array elements may not have always the same items (and the others is not calculated correctly).

2021-07-23 16:53 UTC, h-kataria commented
@brumik please re-review

2021-07-26 11:29 UTC, brumik requested changes
Looks good now, I have a few typing saver tricks here :). The only issue I found is the missing bar from the top of the template:

**Cloud/beta (before)**:
![Screenshot from 2021-07-26 13-26-08](https://user-images.githubusercontent.com/8531681/126981619-5390ede1-ef31-4df7-84b7-4b142e3b78d7.png)

**After:**
![Screenshot from 2021-07-26 13-26-02](https://user-images.githubusercontent.com/8531681/126981651-8dbdac64-e735-4276-b595-6fc8210a0a65.png)

Is this intentional?

2021-07-26 11:29 UTC, brumik commented on src/Components/ModalContents.js
> +      value: stats.items[0].total_count
Here we could use the `??` operator (`stats.items[0]?.total_count ?? 'Unavaiable`). The `??` chceks for null or undefined and returns the value if it defined otherwise it returns the param on the right side (Unavaiable here)

2021-07-26 11:29 UTC, brumik commented on src/Components/ModalContents.js
> +        stats?.items?.length > 0 &&
It is working with: `stats?.items[0]?.name ?? `No template name` too :)

2021-07-26 14:15 UTC, h-kataria commented
> Looks good now, I have a few typing saver tricks here :). The only issue I found is the missing bar from the top of the template:
> 
> **Cloud/beta (before)**:
> ![Screenshot from 2021-07-26 13-26-08](https://user-images.githubusercontent.com/8531681/126981619-5390ede1-ef31-4df7-84b7-4b142e3b78d7.png)
> 
> **After:**
> ![Screenshot from 2021-07-26 13-26-02](https://user-images.githubusercontent.com/8531681/126981651-8dbdac64-e735-4276-b595-6fc8210a0a65.png)
> 
> Is this intentional?

@brumik resolved this issue, good catch. took care of other comments as well

2021-07-26 16:07 UTC, brumik approved these changes
All looking great :+1:

2021-07-26 21:08 UTC, merged