Quality of code fixes
RedHatInsights/tower-analytics-frontend pull request #554
Opened 2021-08-06 12:06 UTC by brumik

Planned to be a bigger PR but creating at least with the fixes.

2021-08-09 17:17 UTC, h-kataria commented on src/Containers/JobExplorer/JobExplorer.js
> -  useEffect(() => {
@brumik is this piece of code here and in other modules redundant?

2021-08-09 17:18 UTC, h-kataria reviewed
other than one question on deleted code, this looks good to me

2021-08-09 22:55 UTC, knightsean00 requested changes
We should probably fix up the linting errors that GitHub raised (using variables before being defined) just so we don't have these errors in the future

2021-08-10 07:28 UTC, brumik commented on src/Containers/JobExplorer/JobExplorer.js
> -  useEffect(() => {
Yes, since the navigation update when doing history.push to other pages the crc router updates, so we don't need to hack it.

2021-08-10 07:32 UTC, brumik commented
@knightsean00 I would like to have it for error in the future. As you can see I set ts to `error` and js to `warn`. This is because last times I discovered we have a lot of first use then define cases. I would fix it as we touch things. The warn is tho show where are the cases. Or I can make a followup PR which refactors all of use before define problems, but I don't think this belongs here.

2021-08-10 13:31 UTC, h-kataria approved these changes

2021-08-10 16:46 UTC, knightsean00 approved these changes

2021-08-10 16:49 UTC, merged