[Do not merge] PDF download modal UI
RedHatInsights/tower-analytics-frontend pull request #657
Opened 2021-11-09 16:22 UTC by skochay330

Created a modal to display when PDF download button is clicked, which allows the user to choose if they would like to download a report which contains only the current page, all items (if less than 100), or top 100 (if more than 100). Export button is disabled if no option is selected, and only one option can be selected at a time.

Jira Issue: https://issues.redhat.com/browse/AA-867

![Screen Shot 2021-11-09 at 11 11 46 AM](https://user-images.githubusercontent.com/89094075/140962672-3f310012-d6f4-43fb-9011-8466f916a1f9.png)
![Screen Shot 2021-11-09 at 11 16 48 AM](https://user-images.githubusercontent.com/89094075/140962667-dd7abb84-e890-4933-9da1-6bb5f85e2d65.png)
![Screen Shot 2021-11-09 at 11 11 54 AM](https://user-images.githubusercontent.com/89094075/140962671-f27299a8-2a9b-4fe8-a1cf-50ea07ba1286.png)

2021-11-10 13:59 UTC, brumik requested changes
This looks good, but I think it could be better:
1. (This comment depends on the backend) There will be more options in the future, such as export as csv. Therefore I would recomment to add instead of `optionSelected` an `options` field which would be an array where we can pass both `csv/pdf` and `limit:10/limit:100` value. I would also recommend using a limit passed to the backend with `:` as a delimiter.
2. Please move the modal window into its own component. Then the button would not get too big, and logically I think it makes sense to have the logic separate. The modal could return only one field `options` which I described above (even if it is not in the API like this)
3. Since the user cannot export it without selecting an option, why would we not mark the `limit:10` option as default. This would save a click in most of the use cases for the users, which is always welcome :)

2021-11-10 13:59 UTC, brumik commented on src/Components/Toolbar/DownloadPdfButton.js
> +            variant="primary"
For all buttons please prefer to use the variant constant: `ButtonVariant.xy`

2021-11-10 13:59 UTC, brumik commented on src/Components/Toolbar/DownloadPdfButton.js
> +            variant="link"
Same as ^

2021-11-10 17:29 UTC, jlmitch5 approved these changes
I disagree with @brumik's proposed changes.  In terms of options, this is a good level of abstraction for the time being, and I don't think things are at the level where we get much value out of moving this to a separate file.  We can make changes to handle these things in the future, once we have more defined requirements around further options.

2021-11-11 08:07 UTC, brumik requested changes
If @jlmitch5 approves then OK for the code changes. However what John did not see (and me neither on the first run) that there is a bug:

You are using the PF component mixed (half managed half non managed state), so the radio in the ui shows the switching correctly, but both of the states `isCurrent` and `isTotal` will be true if you click on both of them and then export. 

You can fix this by managing the state completely by adding the `isChecked` property to the radio button. Then I would unify the two states into one (so `isTotalCount` => true then exporting 100 if false then just the current). this way we have less state to manage. 

I would like to see this PR tested with the API working before approving and merging. Is there a backend work on this?

2021-11-11 08:07 UTC, brumik commented on src/Components/Toolbar/DownloadPdfButton.js
> +  optionSelected,
This is not passed to this component. Did you wanted to do something with it?

2021-11-11 08:07 UTC, brumik commented on src/Components/Toolbar/DownloadPdfButton.js
> +        optionSelected,
I think this line would be something else, depending what the api waits along the lines:
```js
x_tick_format: xTickFormat,
optionSelected: isTotalCount ? 'totalCount' : 'current' // I don't know what the api wants
```

2021-11-11 08:07 UTC, brumik commented on src/Components/Toolbar/DownloadPdfButton.js
> +  const [isTotalCount, setIsTotalCount] = useState(false);
One state is enough as I mentioned in the review above

2021-11-11 08:07 UTC, brumik commented on src/Components/Toolbar/DownloadPdfButton.js
> +              onChange={() => setIsCurrent(true)}
Here you need to add `isChecked` as mentioned above.

(Example from PF docs https://codesandbox.io/s/3p7uc)

2021-11-15 15:37 UTC, h-kataria commented
PDF generator MR: 
PDF Generator MR: https://gitlab.cee.redhat.com/automation-analytics/pdf-generator/-/merge_requests/26

Backend MR: https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/287

2021-11-16 07:14 UTC, brumik commented on src/Components/Toolbar/DownloadPdfButton.js
> +        showExtraRows: isCurrent ? false : true,
Is current is a boolean, you don't need to use a ternary operator (and when you want to convert something else to boolean you can use `!!someStringVar` )

2021-11-16 07:17 UTC, brumik commented on src/Components/Toolbar/DownloadPdfButton.js
> +            onClick={() => request() && setIsExportModalOpen(false)}
I don't think the `request()` is returning anything, but if it returns false the model will not close, and as we are using another modal for error reporting this could lead to bugs. Consider using a function with these two expressions inside.

2021-11-16 07:19 UTC, brumik approved these changes
Those two comments above are small improvements. Otherwise this PR looks good for me :+1:

2021-11-16 22:14 UTC, h-kataria approved these changes

2021-11-17 14:36 UTC, merged