[Waiting for #660][AA-891] Making schema more static
RedHatInsights/tower-analytics-frontend pull request #661
Opened 2021-11-16 11:51 UTC by brumik

This also fixes some bugs concerning the switches from this issue: https://issues.redhat.com/browse/AA-846

2021-11-18 02:02 UTC, jlmitch5 requested changes
This is looking good!  I just have a few notes about changes regarding readability, consistency and common usage as we have in our other instances of useRequest.

2021-11-18 12:04 UTC, brumik commented on src/Containers/Reports/Shared/schemas/affectedHostsByPlaybook.ts
> +  componentName: ReportLayout.DEFAULT,
I think it would make a sense to keep this required, as when we accidentally change the default to something else, there is less space for bugs and it is adding just one line to every report.

2021-11-18 12:05 UTC, brumik commented on src/Containers/Reports/Layouts/index.ts
> +  DEFAULT = 'default',
:+1:

2021-11-18 12:06 UTC, brumik commented on src/Containers/Reports/Shared/schemas/index.ts
>    const moduleReportsEnabled = useFeatureFlag(ValidFeatureFlags.moduleReports);
I think we can talk about it and implement something like this in a future PR

2021-11-18 12:07 UTC, brumik commented on src/Containers/SavingsPlanner/Add/index.js
> +    useCallback(() => readPlanOptions({}), []),
I think explicitly setting this as an empty object is better for one reason:
1. All the other endpoints expect a param, so it is much easier to consolidate all the read endpoint when you need to pass the same thing to all of them.

2021-11-18 12:11 UTC, brumik commented on src/Containers/Reports/Layouts/index.ts
> +import DefaultReport from './Default/';
Yes, you are right. Personally I would like to include the in the name the `component` so it indicates that it maps to a component, rather than just switches. Maybe we could go for the `layoutComponent`? Since it is not really a custom one anymore as all the reports has exactly one.

2021-11-18 12:13 UTC, brumik commented on src/Api/api.ts
> + * function which handles it. It is not covering endpoints which
If we are sure we won't use it in the future for something else, I could move this function to the Reports folder as an utility. That could ease all the above mentioned concerns.

2021-11-18 12:19 UTC, brumik commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.js
> +    (qp) => endpointFunctionMap(optionEndpoint)(qp),
Can we have a conversation about it? I can do this this for this time but there are two reasons I think the non memoized is better:
1. Memozied void functions are non typecheckable at all.
2. The results are the same
3. The format I am trying to push for is more readable in terms that you have to look only the `useEffect` functions which are `queryParams` dependent to know what will change when it is updated.

I think you know I never understood and liked the double memoization of something that we always update when needed. The power of memoization wanishes if you always update it before invocation it. So without that performance gain we are just introducing a harder to follow code.

2021-11-18 12:20 UTC, brumik commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.js
> +  optionEndpoint,
:+1:

2021-11-18 12:22 UTC, brumik commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.js
>      ...api
https://github.com/RedHatInsights/tower-analytics-frontend/pull/661/files/3f03019da4950cb9f882afb09fc5765462e0a23c#diff-47794278eb4c182ec8ef1449bded4a8812c6aa78c0c00dbdc344898fc1ad6ff2L299

Error and loading screens

2021-11-18 14:45 UTC, brumik commented on src/Containers/Reports/ReportsRouter.tsx
> +import Details from './Show';
:+1:

2021-11-18 14:50 UTC, brumik commented on src/Containers/Reports/Layouts/index.ts
> +import DefaultReport from './Default/';
:+1:

2021-11-18 14:53 UTC, brumik commented on src/Api/api.ts
> + * function which handles it. It is not covering endpoints which
I leaving it here and updating the comment to be more clear

:+1:

2021-11-18 14:59 UTC, brumik commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.js
> +    (qp) => endpointFunctionMap(optionEndpoint)(qp),
:+1: 

I'll change it back and open a ticket for this specific issue in Jira

2021-11-18 16:52 UTC, brumik commented
@jlmitch5 I also fixed some schema issues, so now the grouped bar chart does not have this huge offset from the sides, but it is calculated by the charting library and it is aligning really nicely with the sides. This was a more obvious issue on a less than 1200px wide screen :) No jira ticket for that one.

2021-11-23 16:46 UTC, jlmitch5 approved these changes

2021-11-23 16:46 UTC, merged