pipeline updates
RedHatInsights/tower-analytics-frontend pull request #712
Opened 2022-01-04 15:10 UTC by dmzoneill

2022-01-05 14:58 UTC, jameswnl requested changes

2022-01-05 14:58 UTC, jameswnl commented on pr_check.sh
>  IQE_FILTER_EXPRESSION=""
remove Line37-39

2022-01-05 18:14 UTC, jameswnl commented on package.json
> +    "deploy-only": "npm-run-all build:prod",
these changes are not needed any more. just use the `deploy` would do

2022-01-05 18:15 UTC, jameswnl commented on .travis/pr_build.sh
> +npm run deploy-only && curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
change `deploy-only` to `deploy`

2022-01-07 14:31 UTC, brumik approved these changes
LGTM

2022-01-10 12:16 UTC, merged