[WIP] - Added UI to be able to send an email request to backend server
RedHatInsights/tower-analytics-frontend pull request #715
Opened 2022-01-05 16:33 UTC by h-kataria

https://issues.redhat.com/browse/AA-825

Modal with Email radio button and email info fields
![Screen Shot 2022-01-05 at 11 30 13 AM](https://user-images.githubusercontent.com/3450808/148253401-12005f74-6e10-47c2-97b4-04f31a1a5924.png)

Email
![Screen Shot 2022-01-05 at 10 54 05 AM](https://user-images.githubusercontent.com/3450808/148253413-ebe617ed-fc96-4875-a88f-5f0a3239555a.png)

Notification email was sent successfully
![Screen Shot 2022-01-05 at 10 53 45 AM](https://user-images.githubusercontent.com/3450808/148253421-4a2c992c-9793-46ce-b8b7-25624c53515f.png)

Notification while email is being processed
![Screen Shot 2022-01-05 at 10 53 01 AM](https://user-images.githubusercontent.com/3450808/148253447-81e11567-e184-4c25-ab44-da2a84577108.png)

Notification with Error sending an email
![Screen Shot 2022-01-05 at 10 51 12 AM](https://user-images.githubusercontent.com/3450808/148253455-4a3d61c3-e3b6-4996-87ba-09a478c2422c.png)

2022-01-06 09:24 UTC, brumik reviewed
This is not a review. 

I think this feature will be great and even in WIP is looking pretty good. I looked into the code and made some suggestions. 

Also it needs rebase and linting :)

2022-01-06 09:24 UTC, brumik commented on src/Api/types.ts
> +  failure: NotificationAsyncFunction;
success === resolved
failure === rejected

2022-01-06 09:24 UTC, brumik commented on src/Components/Toolbar/DownloadPdfButton.tsx
> +            <Button
To not to mix two types of download logic I would create:
`DownloadPDFButton({ closeModalFnc, pdfParams });`
`EmailPDFButton({ closeModalFnc, pdfParams });`
Where each would contain it's own logic. The modal could stay as their parent component.

2022-01-06 09:24 UTC, brumik commented on src/Components/Toolbar/DownloadPdfButton.tsx
> +              <EmailSend emailInfo={emailInfo} onChange={setEmailInfo} />
This is cool :+1:

2022-01-06 09:24 UTC, brumik commented on src/Components/Toolbar/DownloadPdfButton.tsx
> +                  isChecked={downloadType === 'email'}
Disclaimer: I was not at any UX designs for this feature.

I think if we would make a checkbox next to the button that would say: 
* [ ] Send Email
Then we could show always only one button instead of disabling them and the `current` / `all rows` could be still used to change how many data should be in the report.

2022-01-06 09:24 UTC, brumik commented on src/store/pdfDownloadButton/actions.ts
> +const success = (id: string) => ({
same as before, success is resolved

2022-01-06 09:24 UTC, brumik commented on src/store/pdfDownloadButton/actions.ts
> +const failure = (id: string, message?: string) => ({
failure === rejected

2022-01-06 09:24 UTC, brumik commented on src/store/pdfDownloadButton/types.ts
> +  failure = `EMAIL_FAILURE`,
these two won't be needed I believe

However if we need to keep it let's namespace it with prepending it with the name of the reducer. This way you can make sure that if in different reducers you have an action with the same name (`EMAIL_SUCCESS` for example) then the dispatch won't trigger the actions in both reducers.

2022-01-06 15:18 UTC, h-kataria commented on src/Components/Toolbar/DownloadPdfButton.tsx
> +                  isChecked={downloadType === 'email'}
Thanks for the feedback, we can discuss this on the UX call next week. We haven't had any UX on this feature yet, this is the first cut of the Email feature and was designed by me to show how it works.

2022-02-09 22:44 UTC, jlmitch5 requested changes
Very good! just a few details here and there

2022-02-09 22:44 UTC, jlmitch5 commented on src/Api/methods.ts
> +    else dispatch(addNotification(notif.failure(notif.id)));
lets use notif.rejected instead of creating the new notif.failure?

2022-02-09 22:44 UTC, jlmitch5 commented on src/store/pdfDownloadButton/actions.ts
> +  autoDismiss: false,
auto-dismiss should be true, or rather, i think we can remove this custom prop and just go w default behavior for this.

2022-02-09 22:44 UTC, jlmitch5 commented on src/Components/Toolbar/EmailSend.tsx
> +                <b>{name}</b>: {emails.join(', ')}
looks like the linter wants us to type emails...I believe explicitly calling it an array of strings would fix it.  or typing emailInfo.users as an array of objects with name and emails props

2022-02-09 22:44 UTC, jlmitch5 commented on src/Components/Toolbar/EmailSend.tsx
> +        <Select
looks like all aria stuff is done correctly here, nice!  would you mind testing to make sure the form can be navigated completely with keyboard (tab/etc.)

2022-02-09 22:44 UTC, jlmitch5 commented on src/Components/Toolbar/EmailSend.tsx
> +  const onSelectionChange = (field: string, val: string) => {
very nice, this form is pretty easy to understand, parse and cleanly written

2022-02-09 22:44 UTC, jlmitch5 commented on src/Components/Toolbar/EmailSend.tsx
> +    users: Record<string, string | string[] | any>[];
type here seems a bit strange...why not just string[]?

2022-02-09 22:44 UTC, jlmitch5 commented on src/Components/Toolbar/DownloadPdfButton.tsx
> +              <EmailSend
Let's call this EmailDetailsForm

2022-02-09 22:44 UTC, jlmitch5 commented on src/Components/Toolbar/DownloadPdfButton.tsx
> +import React, { FC, useEffect, useState } from 'react';
This is still readable, but I do feel like it is getting a bit long.  At this point, it probably would benefit from an abstraction of pdf download button and the modal that opens into two separate components.

2022-02-14 18:01 UTC, jlmitch5 approved these changes
Very nice, code looks good. remove that comment, see which casts can be successfully removed

2022-02-14 18:01 UTC, jlmitch5 commented on src/Components/Toolbar/types.ts
> +  //email: string;
remove comment?

2022-02-14 22:37 UTC, h-kataria commented on src/Components/Toolbar/types.ts
> +  //email: string;
this line needs to stay, we need to uncomment and adjust code to read email of RBAC group principal instead of username in real environment

2022-02-28 19:15 UTC, merged