[WIP] Preserve ROI report params in DB
RedHatInsights/tower-analytics-frontend pull request #740
Opened 2022-02-04 12:36 UTC by ZitaNemeckova

Fixes https://issues.redhat.com/browse/AA-1007

TODO: 
- [ ] rbac check
- [ ] changes saved in DB
- [ ] values read from api not default

### RBAC for an user with only read rights
Before:
<img width="1325" alt="Screenshot 2022-02-04 at 13 34 53" src="https://user-images.githubusercontent.com/9210860/152530004-760455f6-e4d4-4e5a-93fb-e145b0472af8.png">

After:
<img width="1323" alt="Screenshot 2022-02-03 at 13 19 28" src="https://user-images.githubusercontent.com/9210860/152529899-0127e85b-9bd7-4c69-847f-be5627fbf4f4.png">

2022-02-09 11:27 UTC, ZitaNemeckova commented
@h-kataria can you please review. It's not perfect but I need a new set of eyes on it and a pointer how to add alerts when saving fails.

2022-02-14 14:13 UTC, jlmitch5 requested changes
looking good, just a couple things

2022-02-14 14:13 UTC, jlmitch5 commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
> +    const prom = saveROI(
can we use async/await here?

if you hadn't seen that syntax before, just a few things:
- mark the function as async
- rewrite the promise call as.

```
try {
  await getROISaveData
} catch (err) {
  err handling (which should probably be surfaced someway, not just a console.log)
}
// stuff in .then
```

2022-02-14 14:13 UTC, jlmitch5 commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
> +    const prom = saveROI(getROISaveData(updatedData));
same here with the async/await

2022-02-14 14:13 UTC, jlmitch5 commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
> +    const prom = saveROI(getROISaveData(updatedData));
same here async/await

2022-02-14 14:13 UTC, jlmitch5 commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
> +    return !!api.result.rbac?.perms?.read;
nice and clean!

2022-02-14 14:13 UTC, jlmitch5 commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
> +   * Set cost from API on load. Don't reload it.
nice comment here, it wouldn't have been clear to me that this wasn't setting it every time they change without it.

2022-02-14 16:20 UTC, ZitaNemeckova commented on src/Api/types.ts
> +  templates_manual_equivalent?: {
@jlmitch5 It's according to what names API expects. Except  for`template_is`. That  is a typo (and fixed).

2022-02-15 23:02 UTC, h-kataria commented
@ZitaNemeckova I found lost $10

the issue is caused by the code that calculates `costManual` and `costAutomation` default values in the report vs the old ROI screen, compare these two blocks of code, in the older version, costAutomation value defaults to 20, but in the new version it is being returned as 25 from API, so either that's a bug or need to adjust the tests appropriately.

Old ROI screen code:
https://github.com/RedHatInsights/tower-analytics-frontend/blob/devel/src/Containers/AutomationCalculator/AutomationCalculator.js#L77-L78

New code from changes in this PR for ROI report:
https://github.com/RedHatInsights/tower-analytics-frontend/pull/740/files#diff-3bfe0ae51512c2bb1ca6456a2679e8328a32f5035d3d70593504a1bf63399228R253-R258

2022-02-16 18:17 UTC, h-kataria commented
> @h-kataria can you please review. It's not perfect but I need a new set of eyes on it and a pointer how to add alerts when saving fails and failing tests.

Can we add a toast notification when save fails with error info, that will not be auto-dismissed, what do you think @jlmitch5

2022-02-17 11:47 UTC, ZitaNemeckova commented
@h-kataria Alert resolved. It's completely ready for review :)

2022-02-17 15:08 UTC, jlmitch5 approved these changes
Looks great!

2022-02-17 15:09 UTC, merged