[WIP] - Aa 970 email phase2
RedHatInsights/tower-analytics-frontend pull request #772
Opened 2022-03-11 17:51 UTC by h-kataria

2022-03-29 20:27 UTC, jlmitch5 requested changes
Looks good!  My only comment is seeing if there might be a more "secure" token generation method built-in to JS available.

Also, for typescript, I think we should try to fix the typescript annotations that are failing and showing up as comments.  If nothing else, lets disable these rules.  That being said, it does seem like we have quite a lot of disabling comments throughout here, and it may be worth doing a pass to see how much typescript annotations we can add.

Finally, may be good to have a few jest tests

2022-03-29 20:27 UTC, jlmitch5 commented on src/Components/Toolbar/DownloadButton/Steps/EmailDetails/SendEmail.tsx
> +  return parseInt(String(min + Math.random() * (max - min)));
may be worth to double check if there are any built in javascript functions using a secure algorithm in place of this.  I couldn't find any by quickly googling, but there may be something on the MDN

2022-04-01 14:08 UTC, ZitaNemeckova commented on src/Components/Toolbar/DownloadButton/Steps/EmailDetails/SendEmail.tsx
> +  return Math.random(0).toString(36).substring(2, 16);
`Math.randm()` === `Math.random(0)`

2022-04-01 14:25 UTC, ZitaNemeckova commented on src/Components/Toolbar/DownloadButton/Steps/EmailDetails/SendEmail.tsx
> +    emailAction(
This is either missing `token` or `token` should be optional.

2022-04-01 14:31 UTC, ZitaNemeckova commented on src/store/pdfDownloadButton/actions.ts
> +  token: string
`token` should be either optional or added to all function calls.

2022-04-01 15:56 UTC, ZitaNemeckova commented on src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.tsx
> +      selectedRbacGroups = revisedGroups;
This needs to be reworked so it's not trying to assign new value to `const selectedRbacGroups `. `const` cannot be changed (probably working because of some compiling magic).

2022-04-01 15:56 UTC, ZitaNemeckova commented on src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.tsx
> +const EmailDetails = ({ options, formData, dispatchReducer }) => {
`const EmailDetails = ({ options, formData, dispatchReducer }: { options: any; formData: any; dispatchReducer: (e: any) => void }) => {` if possible `any` should be a concrete type.

2022-04-01 15:56 UTC, ZitaNemeckova commented on src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.tsx
> +    return rbacGroupsFromApi.find((group) => group.uuid === key)?.name;
Something like this ` return rbacGroupsFromApi.find((group: RbacGroupFromApi) => group.uuid === key)?.name;`

2022-04-01 15:56 UTC, ZitaNemeckova commented on src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.tsx
> +        ({ uuid }) => uuid === groupToChange
`({ uuid }: {uuid: string}) => uuid === groupToChange`

2022-04-01 15:56 UTC, ZitaNemeckova commented on src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.tsx
> +          {users.map(({ name, emails }, i) => {
`{users.map(({ name, emails } : {name: string, emails: any[]}, i: number) => {` If possible replace `any` with something more concete.

2022-04-01 15:56 UTC, ZitaNemeckova commented on src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.tsx
> +    const index = users.findIndex((object) => object.uuid === userHash.uuid);
`const index = users.findIndex((object: {uuid: any}) => object.uuid === userHash.uuid);` if possible replace `any` with something more concrete :)

2022-04-01 15:56 UTC, ZitaNemeckova commented on src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.tsx
> +          setValue={(e) => onExpiryChange(e)}
`setValue={(e) => onExpiryChange(e as string)}`

2022-04-02 00:44 UTC, h-kataria commented
@jlmitch5 ready for another review, took care of most of the ts comments/errors and added jest tests.

2022-04-04 14:48 UTC, jlmitch5 requested changes
a few comments, and looks to be a few files that still have the typescript compiler disabled

2022-04-04 14:48 UTC, jlmitch5 commented on src/Components/Toolbar/DownloadButton/index.test.js
> +    // expect(screen.getByText('Top workflows'));
should these be removed?

2022-04-04 14:48 UTC, jlmitch5 commented on src/Components/Toolbar/DownloadButton/index.tsx
> +  // const title = `Export report <font size={2}>| ${name}</font>`;
should we remove?

2022-04-04 14:48 UTC, jlmitch5 commented on src/Components/Toolbar/DownloadButton/index.tsx
> +// @ts-nocheck
this file is not being checked for ts

2022-04-04 14:48 UTC, jlmitch5 commented on src/Components/Toolbar/DownloadButton/useOptionsData.tsx
> +// @ts-nocheck
this file is not being checked for ts

2022-04-04 14:48 UTC, jlmitch5 commented on src/Containers/DownloadReport/DownloadReport.tsx
> +// @ts-nocheck
this file is not being checked for ts

2022-04-04 18:01 UTC, h-kataria commented on src/Containers/DownloadReport/DownloadReport.tsx
> +// @ts-nocheck
@jlmitch5 this file is almost identical to https://github.com/RedHatInsights/tower-analytics-frontend/blob/devel/src/Containers/Reports/Layouts/Standard/ReportCard.tsx, it is difficult to add disable comments on specific lines as an inline comment because those lines are split into multiple lines, due to linter/prettier extensions.
We can address this one along with other files in the es-lint cleanup task. what do you think?

2022-04-05 00:07 UTC, jlmitch5 approved these changes

2022-04-05 00:07 UTC, jlmitch5 commented
Looks great, great job on this!

2022-04-05 20:47 UTC, merged