[AA-1075] Report preview UX fixes
RedHatInsights/tower-analytics-frontend pull request #774
Opened 2022-03-22 21:21 UTC by skochay330

Condensed and standardized the height of the preview pane for all reports. 

Jira issue: https://issues.redhat.com/browse/AA-1075

Before: 
<img width="1207" alt="Screen Shot 2022-03-22 at 5 18 37 PM" src="https://user-images.githubusercontent.com/89094075/159577845-03c8b79d-543f-47d9-8518-d420ccc49127.png">

After: 
<img width="1207" alt="Screen Shot 2022-03-22 at 5 18 01 PM" src="https://user-images.githubusercontent.com/89094075/159577847-54f1be6e-82ca-4169-af2b-dbd50e5d711d.png">

2022-03-23 19:52 UTC, h-kataria commented on src/Components/ApiStatus/NoData.tsx
> +  <EmptyState variant={EmptyStateVariant.full} style={{ minHeight: '400px' }}>
@skochay330 do we need this change in this PR?

2022-03-23 20:03 UTC, skochay330 commented on src/Components/ApiStatus/NoData.tsx
> +  <EmptyState variant={EmptyStateVariant.full} style={{ minHeight: '400px' }}>
I believe we do, because the goal is to make sure the pane is the same height at all times. In a case where there is no data to display, we want to make sure the pane remains the same size rather than shrinking.

2022-03-24 13:39 UTC, h-kataria commented
@ZitaNemeckova please review

2022-03-24 13:43 UTC, h-kataria commented
LGTM

2022-03-24 13:43 UTC, h-kataria approved these changes

2022-03-24 13:54 UTC, ZitaNemeckova commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
> -                inputs={{ costManual, costAutomation }}
This line needs to stay otherwise user's inputs won't be part of a generated pdf.

2022-03-24 14:05 UTC, ZitaNemeckova commented
@skochay330 This may be out of scope of this PR but it seems to be a bit broken when I change a filter (and attributes are saved to the URL) and then change the previewed report. Sometime it has wrong values in the filter othertimes it crashes. I'd remove all params from the URL. when previewed report changes.

2022-03-24 14:06 UTC, ZitaNemeckova requested changes
`inputs={{ costManual, costAutomation }}` shouldn't be removed.

2022-03-28 10:16 UTC, ZitaNemeckova approved these changes
LGTM 👍

2022-03-28 13:51 UTC, skochay330 commented on src/Containers/Reports/Shared/schemas/hostsByOrganizations.ts
> -  job_type: ['workflowjob', 'job'],
Yes, we want to remove the pre-set filters from both schemas

2022-03-28 15:30 UTC, merged