Fix empty state in ROI report
RedHatInsights/tower-analytics-frontend pull request #803
Opened 2022-06-01 12:23 UTC by ZitaNemeckova

Requirements: when Automation Calculator report has a filter with no results it's possible to work with it like switching off a filter.

Partly fixes https://issues.redhat.com/browse/AA-1014

Before:
<img width="1365" alt="Screenshot 2022-06-01 at 13 50 06" src="https://user-images.githubusercontent.com/9210860/171402926-f64fe58f-3ca9-46cb-92f6-3cc07db51318.png">

After v1:
This is based on the code that was already there.
<img width="1343" alt="Screenshot 2022-06-01 at 13 49 34" src="https://user-images.githubusercontent.com/9210860/171402947-8f1f1e40-535b-44fd-83bd-84be32deb66e.png">

After v2:
This is somewhat consistent with other reports.
<img width="1314" alt="Screenshot 2022-06-01 at 13 56 42" src="https://user-images.githubusercontent.com/9210860/171402970-00ab26d6-1f17-4f88-ace5-7c8c336a9f29.png">

2022-06-01 13:15 UTC, trahman73 commented
@ZitaNemeckova Here is an example of an updated empty state with action that is being used throughout AAP.

![image](https://user-images.githubusercontent.com/13351591/171412993-83bad730-8450-453a-8a2f-ca56798a9cc5.png)

2022-06-01 20:49 UTC, skochay330 requested changes
Other than the component change, works great!

2022-06-01 20:49 UTC, skochay330 commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
> +        <NoData />
Try replacing this line with the code below to better match with feedback from UX. You will need to add a prop to the `EmptyList` component to allow you to add a button while also keeping the 'search' icon [(this is how I have implemented it in my WIP PR)](https://github.com/RedHatInsights/tower-analytics-frontend/pull/796/files#diff-3dba81a841e3492a20e5ab53172bb0be64e9848d66ff2ffa8f3c4611993cfe44R42). Feel free to let me know if you have any questions. 
```suggestion
        <EmptyList
          label={'Clear all filters'}
          title={'No results found'}
          message={
            'No results match the filter criteria. Clear all filters and try again.'
          }
          // addButton={true}
          path={paths.getDetails('automation_calculator')}
        />
```

2022-06-01 21:14 UTC, ZitaNemeckova commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
> +        <NoData />
@skochay330 Thank you for the review I'll have a look at `EmptyList` :) But for some reason my latest changes aren't showing at all. This code is obsolete :(

2022-06-06 15:31 UTC, skochay330 commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
> +            No results match the filter criteria. Clear all filter and try
```suggestion
            No results match the filter criteria. Clear all filters and try
```

2022-06-06 15:31 UTC, skochay330 commented on src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
> +            Clear filter
```suggestion
            Clear all filters
```

2022-06-30 08:35 UTC, merged